-- 召回稽核的語料：每一段是一句合法的 T-SQL，段與段以空白行分開。
-- 稽核在每一個關鍵字、片語字、資料型別與提示的起點問建議清單有沒有它，見 SqlKeywordRecallTests。
-- 名稱只用圖書館領域的名稱；與片語字撞名的名稱會被當成字稽核，要寫成方括號。
-- 新增語句不必改程式；列不出來的字要修。刻意不收的寫法不放進來，理由寫在那一格的文件。

SELECT DISTINCT TOP (10) PERCENT WITH TIES r.ReaderId, r.ReaderName AS Name2
FROM dbo.Lib_Reader AS r
INNER JOIN dbo.Loan l ON l.ReaderId = r.ReaderId
LEFT OUTER JOIN dbo.Copy c WITH (NOLOCK) ON c.CopyNo = l.CopyNo
WHERE r.ReaderId IS NOT NULL AND l.LoanDate BETWEEN '2020-01-01' AND '2020-12-31' OR c.CopyNo LIKE 'A%' ESCAPE '\'
GROUP BY r.ReaderId, r.ReaderName
HAVING COUNT(*) > 1
ORDER BY r.ReaderId DESC, r.ReaderName ASC

SELECT a.CopyNo FROM dbo.Copy a CROSS APPLY dbo.fn_LoansByCopy(a.CopyNo) f OUTER APPLY dbo.fn_LoansByCopy(a.CopyNo) g

SELECT CopyNo FROM dbo.Copy UNION ALL SELECT CopyNo FROM dbo.Loan EXCEPT SELECT CopyNo FROM dbo.Branch INTERSECT SELECT CopyNo FROM dbo.Copy

SELECT CASE WHEN CopyNo IN (1, 2) THEN 'x' WHEN CopyNo IS NULL THEN 'y' ELSE 'z' END FROM dbo.Copy

SELECT CopyNo FROM dbo.Copy WHERE NOT EXISTS (SELECT 1 FROM dbo.Loan WHERE Loan.CopyNo = Copy.CopyNo)

SELECT CopyNo FROM dbo.Copy WHERE CopyNo = ANY (SELECT CopyNo FROM dbo.Loan) AND CopyNo <> ALL (SELECT CopyNo FROM dbo.Branch) AND CopyNo = SOME (SELECT CopyNo FROM dbo.Loan)

SELECT CopyNo FROM dbo.Copy ORDER BY CopyNo OFFSET 10 ROWS FETCH NEXT 5 ROWS ONLY

SELECT CopyNo FROM dbo.Copy ORDER BY CopyNo OFFSET 1 ROW FETCH FIRST 1 ROW ONLY

SELECT SUM(CopyNo) OVER (PARTITION BY BranchId ORDER BY CopyNo ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM dbo.Copy

SELECT SUM(CopyNo) OVER (ORDER BY CopyNo RANGE UNBOUNDED PRECEDING) FROM dbo.Copy

SELECT LoanDate AT TIME ZONE 'UTC' FROM dbo.Loan

SELECT NEXT VALUE FOR dbo.LoanSeq

SELECT CopyNo FROM dbo.Copy WHERE CopyNo IS NOT DISTINCT FROM 1

SELECT CopyNo INTO #t FROM dbo.Copy

SELECT CopyNo FROM dbo.Copy FOR XML PATH('Copy'), ROOT('Copies'), TYPE

SELECT CopyNo FROM dbo.Copy FOR JSON AUTO

SELECT CopyNo FROM dbo.Copy FOR SYSTEM_TIME AS OF '2020-01-01'

SELECT CopyNo FROM dbo.Copy OPTION (RECOMPILE, MAXDOP 1)

SELECT CopyNo FROM dbo.Copy GROUP BY ROLLUP (CopyNo)

SELECT CopyNo FROM dbo.Copy TABLESAMPLE (10 PERCENT)

SELECT p.[1] FROM (SELECT CopyNo, BranchId FROM dbo.Copy) s PIVOT (COUNT(CopyNo) FOR BranchId IN ([1])) p

SELECT CAST(CopyNo AS varchar(10)), CONVERT(nvarchar(20), CopyNo), TRY_CAST(CopyNo AS int) FROM dbo.Copy

SELECT CopyNo FROM dbo.Copy WITH (INDEX (IX_Copy), UPDLOCK)

WITH c AS (SELECT CopyNo FROM dbo.Copy) SELECT CopyNo FROM c

INSERT INTO dbo.Loan (CopyNo, ReaderId) VALUES (1, 2)

INSERT dbo.Loan (CopyNo) SELECT CopyNo FROM dbo.Copy

INSERT INTO dbo.Loan DEFAULT VALUES

INSERT INTO dbo.Loan (CopyNo) OUTPUT inserted.CopyNo VALUES (1)

INSERT TOP (5) INTO dbo.Loan (CopyNo) SELECT CopyNo FROM dbo.Copy

INSERT INTO dbo.Loan (CopyNo) EXEC dbo.usp_Copies

UPDATE dbo.Loan SET CopyNo = 1 WHERE ReaderId = 2

UPDATE TOP (5) dbo.Loan SET CopyNo = 1

UPDATE l SET l.CopyNo = c.CopyNo FROM dbo.Loan l JOIN dbo.Copy c ON c.CopyNo = l.CopyNo

UPDATE dbo.Loan SET CopyNo = 1 OUTPUT deleted.CopyNo WHERE CURRENT OF c

UPDATE STATISTICS dbo.Loan

DELETE FROM dbo.Loan WHERE ReaderId = 2

DELETE TOP (5) FROM dbo.Loan

DELETE dbo.Loan OUTPUT deleted.CopyNo

DELETE l FROM dbo.Loan l JOIN dbo.Copy c ON c.CopyNo = l.CopyNo

TRUNCATE TABLE dbo.Loan

MERGE INTO dbo.Loan AS t USING dbo.Copy AS s ON t.CopyNo = s.CopyNo WHEN MATCHED AND t.ReaderId = 1 THEN UPDATE SET CopyNo = s.CopyNo WHEN NOT MATCHED BY TARGET THEN INSERT (CopyNo) VALUES (s.CopyNo) WHEN NOT MATCHED BY SOURCE THEN DELETE OUTPUT $action;

MERGE dbo.Loan t USING dbo.Copy s ON t.CopyNo = s.CopyNo WHEN MATCHED THEN DELETE;

CREATE TABLE dbo.Loan (LoanId int IDENTITY(1, 1) NOT NULL PRIMARY KEY CLUSTERED, CopyNo int NULL CONSTRAINT FK_Loan_Copy FOREIGN KEY REFERENCES dbo.Copy (CopyNo) ON DELETE CASCADE ON UPDATE NO ACTION, ReaderId int DEFAULT 0, CONSTRAINT UQ_Loan UNIQUE NONCLUSTERED (CopyNo), CHECK (ReaderId > 0))

CREATE TABLE #Loan (CopyNo int, INDEX IX_Loan (CopyNo))

ALTER TABLE dbo.Loan ADD ReaderId int NULL

ALTER TABLE dbo.Loan ADD CONSTRAINT DF_Loan DEFAULT 0 FOR ReaderId

ALTER TABLE dbo.Loan ALTER COLUMN ReaderId bigint NOT NULL

ALTER TABLE dbo.Loan DROP COLUMN IF EXISTS ReaderId

ALTER TABLE dbo.Loan DROP CONSTRAINT DF_Loan

ALTER TABLE dbo.Loan WITH CHECK CHECK CONSTRAINT ALL

ALTER TABLE dbo.Loan NOCHECK CONSTRAINT FK_Loan_Copy

ALTER TABLE dbo.Loan SET (LOCK_ESCALATION = TABLE)

DROP TABLE IF EXISTS dbo.Loan

DROP PROCEDURE IF EXISTS dbo.usp_Copies

DROP VIEW IF EXISTS dbo.v_Copies

DROP FUNCTION IF EXISTS dbo.fn_LoansByCopy

DROP INDEX IX_Loan ON dbo.Loan

CREATE UNIQUE NONCLUSTERED INDEX IX_Loan ON dbo.Loan (CopyNo DESC, ReaderId ASC) INCLUDE (LoanDate) WHERE CopyNo IS NOT NULL WITH (ONLINE = ON)

ALTER INDEX IX_Loan ON dbo.Loan REBUILD

CREATE STATISTICS ST_Loan ON dbo.Loan (CopyNo)

CREATE VIEW dbo.v_Copies WITH SCHEMABINDING AS SELECT CopyNo FROM dbo.Copy

CREATE OR ALTER VIEW dbo.v_Copies AS SELECT CopyNo FROM dbo.Copy

CREATE PROCEDURE dbo.usp_Copies @BranchId int = NULL, @Count int OUTPUT WITH RECOMPILE AS BEGIN SET NOCOUNT ON; SELECT CopyNo FROM dbo.Copy; END

CREATE OR ALTER PROCEDURE dbo.usp_Copies AS SELECT 1

CREATE PROCEDURE dbo.usp_Copies WITH EXECUTE AS OWNER AS SELECT 1

CREATE FUNCTION dbo.fn_Fee (@CopyNo int) RETURNS int WITH SCHEMABINDING AS BEGIN RETURN @CopyNo END

CREATE FUNCTION dbo.fn_LoansByCopy (@CopyNo int) RETURNS TABLE AS RETURN SELECT CopyNo FROM dbo.Loan WHERE CopyNo = @CopyNo

CREATE FUNCTION dbo.fn_Copies () RETURNS @t TABLE (CopyNo int) AS BEGIN INSERT INTO @t (CopyNo) VALUES (1) RETURN END

CREATE TRIGGER dbo.tr_Loan ON dbo.Loan AFTER INSERT, UPDATE AS SET NOCOUNT ON

CREATE TRIGGER dbo.tr_Loan ON dbo.Loan INSTEAD OF DELETE AS SELECT 1

CREATE TRIGGER dbo.tr_Loan ON dbo.Loan FOR DELETE AS SELECT 1

CREATE TRIGGER tr_Ddl ON DATABASE FOR CREATE_TABLE AS SELECT 1

CREATE TRIGGER tr_Logon ON ALL SERVER FOR LOGON AS SELECT 1

ENABLE TRIGGER dbo.tr_Loan ON dbo.Loan

DISABLE TRIGGER ALL ON dbo.Loan

CREATE SEQUENCE dbo.LoanSeq AS int START WITH 1 INCREMENT BY 1

CREATE SYNONYM dbo.Book FOR dbo.Copy

CREATE TYPE dbo.CopyList AS TABLE (CopyNo int)

CREATE SCHEMA Lib AUTHORIZATION dbo

CREATE USER LibUser WITHOUT LOGIN

CREATE USER LibUser FOR LOGIN LibLogin

CREATE LOGIN LibLogin WITH PASSWORD = 'x'

CREATE ROLE LibRole

GRANT SELECT ON dbo.Loan TO LibRole

GRANT EXECUTE ON SCHEMA::dbo TO LibRole WITH GRANT OPTION

DENY SELECT ON dbo.Loan TO LibRole

REVOKE SELECT ON dbo.Loan FROM LibRole

DECLARE @CopyNo int = 1, @Title nvarchar(100), @Due datetime2(0)

DECLARE @Copies TABLE (CopyNo int PRIMARY KEY)

DECLARE c CURSOR LOCAL FAST_FORWARD FOR SELECT CopyNo FROM dbo.Copy

OPEN c

FETCH NEXT FROM c INTO @CopyNo

CLOSE c

DEALLOCATE c

SET NOCOUNT ON

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SET IDENTITY_INSERT dbo.Loan ON

SET @CopyNo = 1

SELECT @CopyNo = CopyNo FROM dbo.Copy

IF @CopyNo = 1 SELECT 1 ELSE SELECT 2

IF EXISTS (SELECT 1 FROM dbo.Loan) BEGIN PRINT 'x' END ELSE BEGIN PRINT 'y' END

WHILE @CopyNo < 10 BEGIN SET @CopyNo += 1; IF @CopyNo = 5 BREAK; CONTINUE END

BEGIN TRY SELECT 1 END TRY BEGIN CATCH THROW; END CATCH

BEGIN TRANSACTION; COMMIT TRANSACTION

BEGIN TRAN; ROLLBACK TRAN

SAVE TRANSACTION sp1

RAISERROR ('x', 16, 1) WITH NOWAIT

RETURN

WAITFOR DELAY '00:00:01'

EXEC dbo.usp_Copies @BranchId = 1, @Count = @CopyNo OUTPUT WITH RECOMPILE

EXECUTE AS USER = 'LibUser'

REVERT

EXEC ('SELECT 1') AT LibServer

PRINT 'x'

USE LibArchive

BACKUP DATABASE LibArchive TO DISK = 'x' WITH COMPRESSION, INIT

BACKUP LOG LibArchive TO DISK = 'x'

RESTORE DATABASE LibArchive FROM DISK = 'x' WITH REPLACE, RECOVERY

DBCC CHECKDB

CHECKPOINT

ALTER DATABASE CURRENT SET RECOVERY SIMPLE

GOTO Done

BULK INSERT dbo.Loan FROM 'x' WITH (FIELDTERMINATOR = ',')

SELECT CopyNo FROM dbo.Copy WHERE CONTAINS(Title, 'x')

SELECT IIF(CopyNo > 1, 1, 0), COALESCE(CopyNo, 0), NULLIF(CopyNo, 0) FROM dbo.Copy

SELECT Title COLLATE Latin1_General_CI_AS FROM dbo.Copy
