-- 召回稽核的語料：每一段是一句合法的 T-SQL，段與段以空白行分開。
-- 稽核在每一個關鍵字、片語字、資料型別、提示與全大寫的字的起點問建議清單有沒有它，見 SqlKeywordRecallTests。
-- 字一律寫成全大寫；名稱只用圖書館領域的名稱、大小寫混合，與片語字撞名的名稱會被當成字稽核，要寫成方括號。
-- 新增語句不必改程式；列不出來的字要修。刻意不收的寫法不放進來，理由寫在那一格的文件。

SELECT DISTINCT TOP (10) PERCENT WITH TIES r.ReaderId, r.ReaderName AS Name2
FROM dbo.Lib_Reader AS r
INNER JOIN dbo.Loan l ON l.ReaderId = r.ReaderId
LEFT OUTER JOIN dbo.Copy c WITH (NOLOCK) ON c.CopyNo = l.CopyNo
WHERE r.ReaderId IS NOT NULL AND l.LoanDate BETWEEN '2020-01-01' AND '2020-12-31' OR c.CopyNo LIKE 'A%' ESCAPE '\'
GROUP BY r.ReaderId, r.ReaderName
HAVING COUNT(*) > 1
ORDER BY r.ReaderId DESC, r.ReaderName ASC

SELECT a.CopyNo FROM dbo.Copy a CROSS APPLY dbo.fn_LoansByCopy(a.CopyNo) f OUTER APPLY dbo.fn_LoansByCopy(a.CopyNo) g

SELECT CopyNo FROM dbo.Copy UNION ALL SELECT CopyNo FROM dbo.Loan EXCEPT SELECT CopyNo FROM dbo.Branch INTERSECT SELECT CopyNo FROM dbo.Copy

SELECT CASE WHEN CopyNo IN (1, 2) THEN 'x' WHEN CopyNo IS NULL THEN 'y' ELSE 'z' END FROM dbo.Copy

SELECT CopyNo FROM dbo.Copy WHERE NOT EXISTS (SELECT 1 FROM dbo.Loan WHERE Loan.CopyNo = Copy.CopyNo)

SELECT CopyNo FROM dbo.Copy WHERE CopyNo = ANY (SELECT CopyNo FROM dbo.Loan) AND CopyNo <> ALL (SELECT CopyNo FROM dbo.Branch) AND CopyNo = SOME (SELECT CopyNo FROM dbo.Loan)

SELECT CopyNo FROM dbo.Copy ORDER BY CopyNo OFFSET 10 ROWS FETCH NEXT 5 ROWS ONLY

SELECT CopyNo FROM dbo.Copy ORDER BY CopyNo OFFSET 1 ROW FETCH FIRST 1 ROW ONLY

SELECT SUM(CopyNo) OVER (PARTITION BY BranchId ORDER BY CopyNo ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM dbo.Copy

SELECT BranchId, STRING_AGG(Title, ', ') WITHIN GROUP (ORDER BY Title DESC) FROM dbo.Copy GROUP BY BranchId

SELECT DISTINCT BranchId, PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY CopyNo) OVER (PARTITION BY BranchId) FROM dbo.Copy

SELECT SUM(CopyNo) OVER (ORDER BY CopyNo RANGE UNBOUNDED PRECEDING) FROM dbo.Copy

SELECT LoanDate AT TIME ZONE 'UTC' FROM dbo.Loan

SELECT LoanDate AT TIME ZONE 'Taipei Standard Time' AT TIME ZONE 'UTC' FROM dbo.Loan

SELECT NEXT VALUE FOR dbo.LoanSeq

SELECT CopyNo FROM dbo.Copy WHERE CopyNo IS NOT DISTINCT FROM 1

SELECT CopyNo INTO #t FROM dbo.Copy

SELECT CopyNo FROM dbo.Copy FOR XML PATH('Copy'), ROOT('Copies'), TYPE

SELECT CopyNo FROM dbo.Copy FOR JSON AUTO

SELECT CopyNo FROM dbo.Copy FOR SYSTEM_TIME AS OF '2020-01-01'

SELECT CopyNo FROM dbo.Copy OPTION (RECOMPILE, MAXDOP 1)

SELECT CopyNo FROM dbo.Copy GROUP BY ROLLUP (CopyNo)

SELECT CopyNo FROM dbo.Copy TABLESAMPLE (10 PERCENT)

SELECT p.[1] FROM (SELECT CopyNo, BranchId FROM dbo.Copy) s PIVOT (COUNT(CopyNo) FOR BranchId IN ([1])) p

SELECT p.[1] FROM (SELECT CopyNo, BranchId FROM dbo.Copy) AS s PIVOT (COUNT(CopyNo) FOR BranchId IN ([1])) AS p

SELECT v.a, d.a FROM (VALUES (1)) AS v(a) CROSS APPLY (SELECT 1 AS a) AS d

SELECT CAST(CopyNo AS varchar(10)), CONVERT(nvarchar(20), CopyNo), TRY_CAST(CopyNo AS int) FROM dbo.Copy

SELECT CopyNo FROM dbo.Copy WITH (INDEX (IX_Copy), UPDLOCK)

WITH c AS (SELECT CopyNo FROM dbo.Copy) SELECT CopyNo FROM c

INSERT INTO dbo.Loan (CopyNo, ReaderId) VALUES (1, 2)

INSERT dbo.Loan (CopyNo) SELECT CopyNo FROM dbo.Copy

INSERT INTO dbo.Loan DEFAULT VALUES

INSERT INTO dbo.Loan (CopyNo) OUTPUT inserted.CopyNo VALUES (1)

INSERT TOP (5) INTO dbo.Loan (CopyNo) SELECT CopyNo FROM dbo.Copy

INSERT INTO dbo.Loan (CopyNo) EXEC dbo.usp_Copies

UPDATE dbo.Loan SET CopyNo = 1 WHERE ReaderId = 2

UPDATE TOP (5) dbo.Loan SET CopyNo = 1

UPDATE l SET l.CopyNo = c.CopyNo FROM dbo.Loan l JOIN dbo.Copy c ON c.CopyNo = l.CopyNo

UPDATE dbo.Loan SET CopyNo = 1 OUTPUT deleted.CopyNo WHERE CURRENT OF c

UPDATE dbo.Loan SET CopyNo = 1 OUTPUT inserted.CopyNo AS NewCopyNo, deleted.CopyNo INTO @Changes WHERE ReaderId = 2

UPDATE l SET CopyNo = 1 OUTPUT inserted.CopyNo AS NewCopyNo INTO @Changes FROM dbo.Loan l

DELETE FROM dbo.Loan WHERE CURRENT OF GLOBAL c

UPDATE STATISTICS dbo.Loan

UPDATE STATISTICS dbo.Loan (ST_Loan) WITH SAMPLE 50 PERCENT, NORECOMPUTE

UPDATE STATISTICS dbo.Loan WITH SAMPLE 1000 ROWS

UPDATE STATISTICS dbo.Loan (ST_Loan) WITH STATS_STREAM = 0x01

UPDATE STATISTICS dbo.Loan (ST_Loan) WITH FULLSCAN, INCREMENTAL = ON, RESAMPLE ON PARTITIONS (1)

CREATE TABLE #LoanStat (LoanId int)
UPDATE STATISTICS #LoanStat

SELECT FILE_NAME(1), FILE_IDEX(FILE_NAME(1)), FILEGROUP_NAME(1), FILEGROUPPROPERTY('PRIMARY', 'IsDefault'), FILEPROPERTY(FILE_NAME(1), 'SpaceUsed'), ORIGINAL_DB_NAME()

DELETE FROM dbo.Loan WHERE ReaderId = 2

DELETE TOP (5) FROM dbo.Loan

DELETE dbo.Loan OUTPUT deleted.CopyNo

DELETE dbo.Loan OUTPUT deleted.CopyNo AS OldCopyNo INTO @Changes WHERE ReaderId = 2

DELETE dbo.Loan OUTPUT deleted.CopyNo, COMPRESS(deleted.CopyNo) AS Packed

DELETE l FROM dbo.Loan l JOIN dbo.Copy c ON c.CopyNo = l.CopyNo

DELETE FROM dbo.Loan FROM dbo.Loan l JOIN dbo.Copy c ON c.CopyNo = l.CopyNo WHERE c.CopyNo = 1

TRUNCATE TABLE dbo.Loan

MERGE INTO dbo.Loan AS t USING dbo.Copy AS s ON t.CopyNo = s.CopyNo WHEN MATCHED AND t.ReaderId = 1 THEN UPDATE SET CopyNo = s.CopyNo WHEN NOT MATCHED BY TARGET THEN INSERT (CopyNo) VALUES (s.CopyNo) WHEN NOT MATCHED BY SOURCE THEN DELETE OUTPUT $action;

MERGE dbo.Loan AS t USING dbo.Copy AS s ON t.CopyNo = s.CopyNo WHEN MATCHED THEN DELETE OUTPUT $action, deleted.CopyNo, s.CopyNo INTO @Changes;

MERGE dbo.Loan t USING dbo.Copy s ON t.CopyNo = s.CopyNo WHEN MATCHED THEN DELETE;

MERGE Loan USING (SELECT * FROM Copy) AS s ON Loan.CopyNo = s.CopyNo WHEN MATCHED THEN DELETE;

DECLARE @a int = 1, @b int = 2;
MERGE Loan USING ((SELECT @a, @b) AS s (c1, c2) JOIN Copy ON s.c1 = Copy.CopyNo) ON Loan.CopyNo = s.c2 WHEN MATCHED THEN DELETE;

SELECT a.ReaderId FROM (Lib_Reader a JOIN Loan AS b ON a.ReaderId = b.ReaderId)

SELECT r.BranchId FROM Branch r JOIN (Lib_Reader a JOIN Loan b ON a.ReaderId = b.ReaderId) ON r.BranchId = a.BranchId

WITH Chain (CopyNo, Depth) AS (SELECT CopyNo, 0 FROM dbo.Copy UNION ALL SELECT Chain.CopyNo, Chain.Depth + 1 FROM Chain JOIN dbo.Loan AS l ON Chain.CopyNo = l.CopyNo) SELECT CopyNo FROM Chain

SELECT CASE WHEN l.CopyNo IS NULL THEN 0 ELSE 1 END FROM dbo.Loan l LEFT JOIN dbo.Copy c ON l.CopyNo = c.CopyNo

DECLARE @AsOf datetime2 = SYSDATETIME();
SELECT a.CopyNo FROM dbo.LoanArchive FOR SYSTEM_TIME AS OF @AsOf AS a JOIN dbo.Copy AS b ON a.CopyNo = b.CopyNo

DECLARE @Loan AS TABLE (LoanId int, CopyNo int);
SELECT c.CopyNo FROM dbo.Copy c JOIN @Loan l ON l.CopyNo = c.CopyNo

SELECT 1 FROM dbo.fn_LoansByCopy('A1') AS s (LoanCount) CROSS APPLY dbo.fn_LoansByCopy(s.LoanCount) AS t

SELECT n.Item FROM dbo.Copy c CROSS APPLY dbo.fn_LoansByCopy(c.CopyNo) AS s (Doc) CROSS APPLY s.Doc.nodes('/Loan') AS n (Item)

CREATE TABLE dbo.Loan (LoanId int IDENTITY(1, 1) NOT NULL PRIMARY KEY CLUSTERED, CopyNo int NULL CONSTRAINT FK_Loan_Copy FOREIGN KEY REFERENCES dbo.Copy (CopyNo) ON DELETE CASCADE ON UPDATE NO ACTION, ReaderId int DEFAULT 0, CONSTRAINT UQ_Loan UNIQUE NONCLUSTERED (CopyNo), CHECK (ReaderId > 0))

CREATE TABLE #Loan (CopyNo int, INDEX IX_Loan (CopyNo))

ALTER TABLE dbo.Loan ADD ReaderId int NULL

ALTER TABLE dbo.Loan ADD CONSTRAINT DF_Loan DEFAULT 0 FOR ReaderId

ALTER TABLE dbo.Loan ALTER COLUMN ReaderId bigint NOT NULL

ALTER TABLE dbo.Loan DROP COLUMN IF EXISTS ReaderId

ALTER TABLE dbo.Loan DROP CONSTRAINT DF_Loan

ALTER TABLE dbo.Loan WITH CHECK CHECK CONSTRAINT ALL

ALTER TABLE dbo.Loan NOCHECK CONSTRAINT FK_Loan_Copy

ALTER TABLE dbo.Loan SET (LOCK_ESCALATION = TABLE)

DROP TABLE IF EXISTS dbo.Loan

DROP PROCEDURE IF EXISTS dbo.usp_Copies

DROP VIEW IF EXISTS dbo.v_Copies

DROP FUNCTION IF EXISTS dbo.fn_LoansByCopy

DROP INDEX IX_Loan ON dbo.Loan

CREATE UNIQUE NONCLUSTERED INDEX IX_Loan ON dbo.Loan (CopyNo DESC, ReaderId ASC) INCLUDE (LoanDate) WHERE CopyNo IS NOT NULL WITH (ONLINE = ON)

ALTER INDEX IX_Loan ON dbo.Loan REBUILD

CREATE STATISTICS ST_Loan ON dbo.Loan (CopyNo)

CREATE STATISTICS ST_Loan ON dbo.Loan (CopyNo) WHERE CopyNo > 0 WITH SAMPLE 10 PERCENT

CREATE VIEW dbo.v_Copies WITH SCHEMABINDING AS SELECT CopyNo FROM dbo.Copy

CREATE OR ALTER VIEW dbo.v_Copies AS SELECT CopyNo FROM dbo.Copy

CREATE PROCEDURE dbo.usp_Copies @BranchId int = NULL, @Count int OUTPUT WITH RECOMPILE AS BEGIN SET NOCOUNT ON; SELECT CopyNo FROM dbo.Copy; END

CREATE OR ALTER PROCEDURE dbo.usp_Copies AS SELECT 1

CREATE PROCEDURE dbo.usp_Copies WITH EXECUTE AS OWNER AS SELECT 1

CREATE FUNCTION dbo.fn_Fee (@CopyNo int) RETURNS int WITH SCHEMABINDING AS BEGIN RETURN @CopyNo END

CREATE FUNCTION dbo.fn_LoansByCopy (@CopyNo int) RETURNS TABLE AS RETURN SELECT CopyNo FROM dbo.Loan WHERE CopyNo = @CopyNo

CREATE FUNCTION dbo.fn_Copies () RETURNS @t TABLE (CopyNo int) AS BEGIN INSERT INTO @t (CopyNo) VALUES (1) RETURN END

CREATE TRIGGER dbo.tr_Loan ON dbo.Loan AFTER INSERT, UPDATE AS SET NOCOUNT ON

CREATE TRIGGER dbo.tr_Loan ON dbo.Loan AFTER INSERT AS INSERT INTO dbo.LoanDetail (CopyNo) SELECT inserted.CopyNo FROM inserted

CREATE TRIGGER dbo.tr_Loan ON dbo.Loan AFTER UPDATE AS UPDATE l SET ReaderId = i.ReaderId FROM dbo.Loan l JOIN inserted i ON i.CopyNo = l.CopyNo WHERE EXISTS (SELECT 1 FROM deleted d WHERE d.CopyNo = i.CopyNo)

ALTER TRIGGER dbo.tr_Loan ON dbo.Loan AFTER DELETE AS IF EXISTS (SELECT * FROM deleted) DELETE dbo.LoanDetail FROM dbo.LoanDetail JOIN deleted ON deleted.CopyNo = LoanDetail.CopyNo

SET LANGUAGE us_english

SET LANGUAGE N'Deutsch'

CREATE TRIGGER dbo.tr_Loan ON dbo.Loan INSTEAD OF DELETE AS SELECT 1

CREATE TRIGGER dbo.tr_Loan ON dbo.Loan FOR DELETE AS SELECT 1

CREATE TRIGGER tr_Ddl ON DATABASE FOR CREATE_TABLE AS SELECT 1

CREATE TRIGGER tr_Logon ON ALL SERVER FOR LOGON AS SELECT 1

ENABLE TRIGGER dbo.tr_Loan ON dbo.Loan

DISABLE TRIGGER ALL ON dbo.Loan

CREATE SEQUENCE dbo.LoanSeq AS int START WITH 1 INCREMENT BY 1

CREATE SYNONYM dbo.Book FOR dbo.Copy

CREATE TYPE dbo.CopyList AS TABLE (CopyNo int)

CREATE SCHEMA Lib AUTHORIZATION dbo

CREATE USER LibUser WITHOUT LOGIN

CREATE USER LibUser FOR LOGIN LibLogin

CREATE LOGIN LibLogin WITH PASSWORD = 'x'

CREATE LOGIN LibLogin WITH PASSWORD = 'x', DEFAULT_LANGUAGE = us_english, CHECK_POLICY = OFF

ALTER LOGIN LibLogin WITH DEFAULT_LANGUAGE = us_english

CREATE USER LibUser WITH PASSWORD = 'x', DEFAULT_LANGUAGE = us_english

ALTER DATABASE CURRENT SET DEFAULT_LANGUAGE = us_english

CREATE ROLE LibRole

CREATE APPLICATION ROLE LibAppRole WITH PASSWORD = 'x', DEFAULT_SCHEMA = dbo

ALTER APPLICATION ROLE LibAppRole WITH NAME = LibAppRole2, DEFAULT_SCHEMA = dbo

GRANT SELECT ON dbo.Loan TO LibRole

GRANT EXECUTE ON SCHEMA::dbo TO LibRole WITH GRANT OPTION

DENY SELECT ON dbo.Loan TO LibRole

REVOKE SELECT ON dbo.Loan FROM LibRole

DECLARE @CopyNo int = 1, @Title nvarchar(100), @Due datetime2(0)

DECLARE @Copies TABLE (CopyNo int PRIMARY KEY)

DECLARE c CURSOR LOCAL FAST_FORWARD FOR SELECT CopyNo FROM dbo.Copy

OPEN c

FETCH NEXT FROM c INTO @CopyNo

FETCH ABSOLUTE 1 FROM GLOBAL c INTO @CopyNo

FETCH RELATIVE @CopyNo FROM GLOBAL c

FETCH PRIOR FROM GLOBAL c

CLOSE c

DEALLOCATE c

SET NOCOUNT ON

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SET IDENTITY_INSERT dbo.Loan ON

SET @CopyNo = 1

DECLARE @CopyCount INT;
SET @CopyCount = 1

DECLARE @CopyCount INT
IF (1 = 1) SET @CopyCount = 1

CREATE PROCEDURE dbo.usp_CountCopies @CopyCount INT AS
BEGIN
SET @CopyCount = 1
END

DECLARE @CopyCount INT;
FETCH NEXT FROM c INTO @CopyCount

DECLARE @CopyCount INT;
FETCH ABSOLUTE 1 FROM GLOBAL c INTO @CopyCount

DECLARE @CopyCount INT;
FETCH PRIOR FROM c INTO @CopyCount

DECLARE @CopyCount AS INT

DECLARE @CopyNo INT, @CopyCount AS INT

CREATE PROCEDURE dbo.usp_CountCopies @CopyCount AS INT AS
SELECT 1

CREATE TABLE dbo.Loan (LoanId INT, CopyCount INT, Total AS (LoanId + CopyCount))

DECLARE @Loan TABLE (LoanId INT, Total AS LoanId * 2)

ALTER TABLE dbo.Loan ADD Total AS (LoanId + 1)

DECLARE @CopyCount INT, @CopyNo VARCHAR(10);
SET @CopyCount = CAST (@CopyNo AS INT)

DECLARE @CopyCount INT, @CopyNo VARCHAR(10);
SET @CopyCount = TRY_CAST (@CopyNo AS INT) + CAST(@CopyNo AS INT)

DECLARE @Embedding VECTOR(3) = '[0.1, 2, 30]', @Doc AS JSON = '{}'

DECLARE @Title NVARCHAR(100) = N'[1, 2, 3]';
SELECT CAST(@Title AS VECTOR(3)), TRY_CONVERT(JSON, @Title)

CREATE TABLE dbo.Loan (LoanId INT, Doc JSON NULL, Embedding VECTOR(3) NOT NULL)

ALTER TABLE dbo.Loan ADD Embedding VECTOR(3) NULL

SELECT @CopyNo = CopyNo FROM dbo.Copy

IF @CopyNo = 1 SELECT 1 ELSE SELECT 2

IF 1 = 1 COMMIT ELSE ROLLBACK

IF 1 = 1 ALTER INDEX Ix ON dbo.Loan REBUILD ELSE PRINT 1

IF 1 = 1 BULK INSERT dbo.Loan FROM 'x' ELSE PRINT 1

IF EXISTS (SELECT 1 FROM dbo.Loan) BEGIN PRINT 'x' END ELSE BEGIN PRINT 'y' END

WHILE @CopyNo < 10 BEGIN SET @CopyNo += 1; IF @CopyNo = 5 BREAK; CONTINUE END

BEGIN TRY SELECT 1 END TRY BEGIN CATCH THROW; END CATCH

BEGIN TRANSACTION; COMMIT TRANSACTION

BEGIN TRAN; ROLLBACK TRAN

SAVE TRANSACTION sp1

RAISERROR ('x', 16, 1) WITH NOWAIT, LOG

RAISERROR ('x', 16, 1) WITH SETERROR, LOG

RETURN

WAITFOR DELAY '00:00:01'

EXEC dbo.usp_Copies @BranchId = 1, @Count = @CopyNo OUTPUT WITH RECOMPILE

EXEC dbo.usp_Copies WITH RESULT SETS ((Branch varchar(10) COLLATE Latin1_General_CI_AS NOT NULL, CopyCount int NULL), (CopyNo int))

EXEC dbo.usp_Copies WITH RECOMPILE, RESULT SETS NONE

EXEC ('SELECT 1') WITH RESULT SETS UNDEFINED

EXEC dbo.usp_Copies WITH RESULT SETS (AS OBJECT dbo.Loan, AS TYPE dbo.CopyList, AS FOR XML)

EXECUTE AS USER = 'LibUser'

REVERT

EXEC ('SELECT 1') AT LibServer

PRINT 'x'

USE LibArchive

BACKUP DATABASE LibArchive TO DISK = 'x' WITH COMPRESSION, INIT

BACKUP LOG LibArchive TO DISK = 'x'

RESTORE DATABASE LibArchive FROM DISK = 'x' WITH REPLACE, RECOVERY

RESTORE LOG LibArchive FROM DISK = 'x' WITH FILE = 2, NORECOVERY

BACKUP DATABASE LibArchive TO DISK = 'a', TAPE = 'b', URL = 'c' MIRROR TO DISK = 'd' MIRROR TO TAPE = 'e' WITH FORMAT, ENCRYPTION (ALGORITHM = AES_256, SERVER CERTIFICATE = LibCert)

RESTORE DATABASE LibArchive FROM TAPE = 'a', DISK = 'b' WITH MOVE 'Lib' TO 'x', MOVE 'Lib_log' TO 'y', RECOVERY

COMMIT TRANSACTION WITH (DELAYED_DURABILITY = ON)

COMMIT WITH (DELAYED_DURABILITY = OFF)

COMMIT TRAN LoanTran WITH (DELAYED_DURABILITY = ON)

DBCC CHECKDB

DBCC CHECKDB (N'LibArchive') WITH NO_INFOMSGS, ALL_ERRORMSGS

DBCC SHOW_STATISTICS ('dbo.Loan', st_CopyNo) WITH STAT_HEADER

DBCC CHECKIDENT ('dbo.Lib_Tag', RESEED, 100)

DBCC CHECKIDENT ('dbo.Lib_Tag', NORESEED)

DBCC CHECKDB (N'LibArchive', REPAIR_REBUILD) WITH NO_INFOMSGS

DBCC SQLPERF (LOGSPACE)

DBCC SQLPERF ('sys.dm_os_wait_stats', CLEAR)

DBCC SHRINKFILE (LibArchive_log, EMPTYFILE)

DBCC SHRINKDATABASE (LibArchive, 10, TRUNCATEONLY)

CHECKPOINT

ALTER DATABASE CURRENT SET RECOVERY SIMPLE

GOTO Done

BULK INSERT dbo.Loan FROM 'x' WITH (FIELDTERMINATOR = ',')

COPY INTO dbo.Loan (LoanId 1, CopyNo DEFAULT 0 2)
FROM 'https://x/loan.csv', 'https://x/loan2.csv'
WITH (FILE_TYPE = 'CSV', CREDENTIAL = (IDENTITY = 'Shared Access Signature', SECRET = 'x'), FIELDQUOTE = '"', FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0A', ENCODING = 'UTF8', DATEFORMAT = 'ymd', MAXERRORS = 10, ERRORFILE = '/errors', COMPRESSION = 'GZIP', FIRSTROW = 2, IDENTITY_INSERT = 'OFF')

COPY INTO dbo.Loan FROM 'https://x/loan.parquet' WITH (FILE_TYPE = 'PARQUET', ERRORFILE = '/errors', ERRORFILE_CREDENTIAL = (IDENTITY = 'Managed Identity'))

SELECT CopyNo FROM dbo.Copy WHERE CONTAINS(Title, 'x')

SELECT IIF(CopyNo > 1, 1, 0), COALESCE(CopyNo, 0), NULLIF(CopyNo, 0) FROM dbo.Copy

SELECT Title COLLATE Latin1_General_CI_AS FROM dbo.Copy

SELECT Title COLLATE DATABASE_DEFAULT FROM dbo.Copy

DECLARE c CURSOR GLOBAL SCROLL FOR SELECT CopyNo FROM dbo.Copy

OPEN GLOBAL c

FETCH FIRST FROM GLOBAL c INTO @CopyNo

FETCH LAST FROM GLOBAL c INTO @CopyNo

CLOSE GLOBAL c

DEALLOCATE GLOBAL c

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'x'

OPEN MASTER KEY DECRYPTION BY PASSWORD = 'x'

CLOSE MASTER KEY

CREATE CERTIFICATE LibCert WITH SUBJECT = 'x'

CREATE CERTIFICATE LibCert ENCRYPTION BY PASSWORD = 'x' WITH SUBJECT = 'x', EXPIRY_DATE = '20301231'

CREATE ASYMMETRIC KEY LibAsymKey WITH ALGORITHM = RSA_2048 ENCRYPTION BY PASSWORD = 'x'

CREATE SYMMETRIC KEY LibSymKey WITH ALGORITHM = AES_256 ENCRYPTION BY CERTIFICATE LibCert

CREATE SYMMETRIC KEY LibSymKey WITH ALGORITHM = AES_256 ENCRYPTION BY PASSWORD = 'x'

CREATE SYMMETRIC KEY LibSymKey WITH ALGORITHM = AES_256 ENCRYPTION BY ASYMMETRIC KEY LibAsymKey

OPEN SYMMETRIC KEY LibSymKey DECRYPTION BY CERTIFICATE LibCert

OPEN SYMMETRIC KEY LibSymKey DECRYPTION BY PASSWORD = 'x'

OPEN SYMMETRIC KEY LibSymKey DECRYPTION BY ASYMMETRIC KEY LibAsymKey WITH PASSWORD = 'x'

CLOSE SYMMETRIC KEY LibSymKey

CLOSE ALL SYMMETRIC KEYS

DROP SYMMETRIC KEY LibSymKey

DROP ASYMMETRIC KEY LibAsymKey

DROP CERTIFICATE LibCert

ALTER MASTER KEY REGENERATE WITH ENCRYPTION BY PASSWORD = 'x'

CREATE DATABASE ENCRYPTION KEY WITH ALGORITHM = AES_256 ENCRYPTION BY SERVER CERTIFICATE LibCert

CREATE CREDENTIAL LibCredential WITH IDENTITY = 'x', SECRET = 'y'

CREATE LOGIN LibKeyLogin FROM ASYMMETRIC KEY LibAsymKey

DROP LOGIN LibKeyLogin

CREATE TABLE dbo.LoanArchive (LoanId int NOT NULL PRIMARY KEY, ValidFrom datetime2 GENERATED ALWAYS AS ROW START NOT NULL, ValidTo datetime2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL, PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LoanArchiveHistory, DATA_CONSISTENCY_CHECK = ON))

ALTER TABLE dbo.LoanArchive SET (SYSTEM_VERSIONING = OFF)

ALTER TABLE dbo.LoanArchive DROP PERIOD FOR SYSTEM_TIME

ALTER TABLE dbo.LoanArchive ADD PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)

-- Uses Lib_Reader.
SELECT 1

SELECT 1
-- next step.
SELECT 2

SELECT CopyNo -- the copy.
FROM dbo.Copy

SELECT CopyNo AS Seq FROM dbo.Copy ORDER BY Seq

INSERT INTO dbo.Loan (CopyNo, ReaderId) VALUES (1, NULL)

DECLARE @Fee int
SET @Fee = IIF(@Fee IS NULL, NULL, 1)

SELECT * FROM OPENROWSET(BULK 'Copy.csv', FORMAT = 'CSV', DATA_SOURCE = 'LibSource') AS c

DECLARE @Doc nvarchar(max) = N'[]'
SELECT * FROM OPENJSON(@Doc)

DECLARE @Handle int
SELECT * FROM OPENXML(@Handle, '/r')

CREATE EXTERNAL TABLE dbo.LoanArchiveFile
WITH (LOCATION = '/loan/', DATA_SOURCE = LibSource, FILE_FORMAT = LibFormat)
AS SELECT LoanId FROM dbo.Loan

DECLARE @Doc nvarchar(max) = N'[]'
SELECT * FROM OPENJSON(@Doc, '$') WITH (CopyNo int, Branch varchar(10))

DECLARE @Handle int
SELECT * FROM OPENXML(@Handle, '/r') WITH (CopyNo int, Branch varchar(10))

CREATE EXTERNAL TABLE dbo.LoanFile (LoanId int, CopyNo int)
WITH (LOCATION = '/loan/', DATA_SOURCE = LibSource, FILE_FORMAT = LibFormat)

CREATE EXTERNAL TABLE dbo.LoanReject (LoanId int)
WITH (LOCATION = '/loan/', DATA_SOURCE = LibSource, FILE_FORMAT = LibFormat, REJECT_TYPE = VALUE, REJECT_VALUE = 0)

SELECT CopyNo INTO dbo.LoanCopy ON [PRIMARY] FROM dbo.Loan WHERE LoanId = 1

CREATE TABLE LibArchive..LoanCopy (LoanId int, CopyNo int)

CREATE TABLE [dbo].[LoanCopy]([LoanId] int NOT NULL, [CopyNo] int NULL)

INSERT BULK dbo.Loan (LoanId int, CopyNo int)

ALTER TABLE dbo.Loan ADD CONSTRAINT PK_Loan PRIMARY KEY (LoanId) WITH (ONLINE = ON)

ALTER INDEX IX_Loan ON dbo.Loan REBUILD WITH (ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 1 MINUTES, ABORT_AFTER_WAIT = SELF)))

ALTER TABLE dbo.Loan SWITCH TO dbo.LoanArchive WITH (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 1 MINUTES, ABORT_AFTER_WAIT = NONE))

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 1

ALTER DATABASE SCOPED CONFIGURATION SET TIME_ZONE = LOCAL

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET ELEVATE_ONLINE = WHEN_SUPPORTED

ALTER MASTER KEY ADD ENCRYPTION BY PASSWORD = 'x'

CREATE TABLE dbo.LoanAudit (LoanId int, ValidFrom datetime2 GENERATED ALWAYS AS ROW START, ValidTo datetime2 GENERATED ALWAYS AS ROW END, CreatedBy varbinary(85) GENERATED ALWAYS AS SUSER_SID START HIDDEN NOT NULL, ChangedBy nvarchar(128) GENERATED ALWAYS AS SUSER_SNAME END, PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo))

ALTER TABLE dbo.Loan ALTER COLUMN CreatedBy varbinary(85) GENERATED ALWAYS AS SUSER_SID START

ALTER SYMMETRIC KEY LibKey ADD ENCRYPTION BY PASSWORD = 'x'

ALTER SERVER AUDIT LibAudit WITH (STATE = ON)

CREATE SERVER AUDIT LibAudit TO FILE (FILEPATH = 'x', MAXSIZE = 10 MB, MAX_ROLLOVER_FILES = 4)

SELECT c.CopyNo FROM VECTOR_SEARCH(TABLE = dbo.Copy AS c, COLUMN = Embedding, SIMILAR_TO = @Probe, METRIC = 'cosine', TOP_N = 10) AS s ORDER BY c.CopyNo

CREATE EXTERNAL DATA SOURCE LibSource WITH (LOCATION = 'hdfs://x', TYPE = HADOOP, CREDENTIAL = LibCredential)

CREATE EXTERNAL FILE FORMAT LibFormat WITH (FORMAT_TYPE = DELIMITEDTEXT, FORMAT_OPTIONS (FIELD_TERMINATOR = ',', FIRST_ROW = 2))

CREATE EXTERNAL TABLE dbo.LoanFeed (LoanId int NOT NULL)
WITH (
DATA_SOURCE = LibSource, LOCATION = '/loan/', FILE_FORMAT = LibFormat)

CREATE EVENT SESSION LibSession ON SERVER
ADD EVENT sqlserver.sql_batch_completed,
ADD EVENT sqlserver.rpc_completed
ADD TARGET package0.ring_buffer

DROP EVENT SESSION LibSession ON SERVER

CREATE EVENT SESSION LibSession ON SERVER ADD EVENT sqlserver.sql_batch_completed ADD TARGET package0.ring_buffer WITH (MAX_MEMORY = 4 MB, MAX_EVENT_SIZE = 1 KB, MAX_DISPATCH_LATENCY = 30 SECONDS)

ALTER TABLE dbo.Loan DROP CONSTRAINT PK_Loan WITH (ONLINE = ON)

ALTER TABLE dbo.Loan ALTER COLUMN Note varchar(100) COLLATE Latin1_General_CI_AS NULL WITH (ONLINE = ON)

ALTER TABLE dbo.Loan ALTER COLUMN Amount decimal(10, 2) NOT NULL WITH (ONLINE = ON)

ALTER TABLE dbo.Loan ALTER COLUMN Total ADD PERSISTED WITH (ONLINE = ON)

ALTER TABLE dbo.Loan ALTER COLUMN LoanId DROP NOT FOR REPLICATION WITH (ONLINE = ON)

ALTER TABLE dbo.Loan REBUILD PARTITION = 1 WITH (ONLINE = ON)

ALTER TABLE dbo.Loan REBUILD WITH (ONLINE = ON)

ALTER INDEX ALL ON dbo.Loan REBUILD PARTITION = 1 WITH (ONLINE = ON)

ALTER INDEX ALL ON dbo.Loan REBUILD PARTITION = ALL WITH (ONLINE = ON)

ALTER TABLE dbo.Loan REBUILD PARTITION = ALL WITH (ONLINE = ON)

DROP INDEX IX_Loan ON dbo.Loan WITH (ONLINE = ON, MOVE TO LibArchive), IX_Copy ON dbo.Copy WITH (ONLINE = ON)

CREATE CLUSTERED COLUMNSTORE INDEX CCI_Loan ON dbo.Loan WITH (ONLINE = ON)

CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_Loan ON dbo.Loan (LoanId) WITH (ONLINE = ON)

ALTER TABLE dbo.Loan DROP COLUMN Note, CONSTRAINT DF_Loan WITH (ONLINE = ON)

BACKUP SERVICE MASTER KEY TO FILE = 'x' ENCRYPTION BY PASSWORD = 'x'

ALTER SERVICE MASTER KEY WITH OLD_ACCOUNT = 'x', OLD_PASSWORD = 'x'

ALTER SERVICE MASTER KEY WITH NEW_ACCOUNT = 'x', NEW_PASSWORD = 'x'

ALTER SERVICE MASTER KEY FORCE REGENERATE

BACKUP MASTER KEY TO FILE = 'x' ENCRYPTION BY PASSWORD = 'x'

RESTORE MASTER KEY FROM FILE = 'x' DECRYPTION BY PASSWORD = 'x' ENCRYPTION BY PASSWORD = 'x'

BACKUP CERTIFICATE LibCert TO FILE = 'x' WITH PRIVATE KEY (FILE = 'x', ENCRYPTION BY PASSWORD = 'x')

CREATE ASYMMETRIC KEY LibAsym FROM ASSEMBLY LibAssembly ENCRYPTION BY PASSWORD = 'x'

ALTER ASYMMETRIC KEY LibAsym WITH PRIVATE KEY (DECRYPTION BY PASSWORD = 'x', ENCRYPTION BY PASSWORD = 'x')

ALTER CERTIFICATE LibCert WITH PRIVATE KEY (FILE = 'x', DECRYPTION BY PASSWORD = 'x', ENCRYPTION BY PASSWORD = 'x')

CREATE CERTIFICATE LibCert FROM FILE = 'x' WITH PRIVATE KEY (FILE = 'x', DECRYPTION BY PASSWORD = 'x', ENCRYPTION BY PASSWORD = 'x')

CREATE SYMMETRIC KEY LibKey WITH KEY_SOURCE = 'x', IDENTITY_VALUE = 'x', ALGORITHM = AES_256 ENCRYPTION BY PASSWORD = 'x'

CREATE ASYMMETRIC KEY LibAsym FROM PROVIDER LibProvider WITH ALGORITHM = RSA_2048 ENCRYPTION BY PASSWORD = 'x'

CREATE SERVER AUDIT SPECIFICATION LibAuditSpec FOR SERVER AUDIT LibAudit ADD (FAILED_LOGIN_GROUP) WITH (STATE = ON)

ALTER SERVER AUDIT SPECIFICATION LibAuditSpec ADD (FAILED_LOGIN_GROUP), DROP (SUCCESSFUL_LOGIN_GROUP) WITH (STATE = ON)

CREATE DATABASE AUDIT SPECIFICATION LibDbAuditSpec FOR SERVER AUDIT LibAudit ADD (SCHEMA_OBJECT_ACCESS_GROUP), ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP) WITH (STATE = ON)

CREATE SECURITY POLICY dbo.LibPolicy ADD FILTER PREDICATE dbo.fn_LoanFilter(ReaderId) ON dbo.Loan WITH (STATE = ON)

CREATE SECURITY POLICY dbo.LibBlockPolicy ADD BLOCK PREDICATE dbo.fn_LoanFilter(ReaderId) ON dbo.Loan AFTER INSERT WITH (STATE = ON)

ALTER SECURITY POLICY dbo.LibPolicy WITH (STATE = OFF)

CREATE SECURITY POLICY dbo.LibMixedPolicy ADD FILTER PREDICATE dbo.fn_LoanFilter(ReaderId) ON dbo.Loan, ADD BLOCK PREDICATE dbo.fn_LoanFilter(ReaderId) ON dbo.Loan BEFORE DELETE WITH (STATE = ON)

CREATE SERVER AUDIT SPECIFICATION LibAuditSpec FOR SERVER AUDIT LibAudit WITH (STATE = OFF)

ALTER DATABASE AUDIT SPECIFICATION LibDbAuditSpec WITH (STATE = OFF)

CREATE SYMMETRIC KEY LibKey2 WITH KEY_SOURCE = 'x', IDENTITY_VALUE = 'x' ENCRYPTION BY PASSWORD = 'x'

CREATE EXTERNAL MODEL LibModel AUTHORIZATION dbo WITH (LOCATION = 'https://x', API_FORMAT = 'Azure OpenAI', MODEL_TYPE = EMBEDDINGS, MODEL = 'x', CREDENTIAL = LibCredential)

CREATE VECTOR INDEX VIX_Copy ON dbo.Copy (Embedding) WITH (METRIC = 'cosine', TYPE = 'diskann')

CREATE EVENT NOTIFICATION LibNotify ON SERVER FOR CREATE_DATABASE TO SERVICE 'LibService', 'current database'

DROP EVENT NOTIFICATION LibNotify, LibNotify2 ON SERVER

CREATE EVENT SESSION LibSession ON DATABASE ADD EVENT sqlserver.sql_batch_completed (SET collect_batch_text = 1), ADD EVENT sqlserver.rpc_completed (ACTION (sqlserver.sql_text)), ADD EVENT sqlserver.error_reported (WHERE severity > 10) ADD TARGET package0.ring_buffer

CREATE COLUMNSTORE INDEX NCCI_Copy ON dbo.Copy (CopyNo) WITH (ONLINE = ON)

ALTER SERVER AUDIT [Lib Audit]
WITH (STATE = OFF)

ALTER SERVER AUDIT LibAudit MODIFY NAME = LibAudit2

ALTER SERVER AUDIT LibAudit REMOVE WHERE

KILL QUERY NOTIFICATION SUBSCRIPTION ALL

KILL STATS JOB 12

SELECT CopyNo FROM dbo.Copy ORDER BY DATEPART(YEAR, LoanDate) DESC, DATEPART(MONTH, LoanDate)

SELECT SUM(Fee) OVER (PARTITION BY BranchId ORDER BY DATEPART(YEAR, LoanDate)) FROM dbo.Loan

SELECT x.Big FROM (VALUES (1)) d (Seq) CROSS APPLY (VALUES (2)) e (Flag) CROSS APPLY (SELECT CAST(Seq AS bigint) AS Big, CAST(Flag AS bit) AS Bit) x

SELECT x.Bit FROM (SELECT 1 AS Branch, 1 AS Fee) s PIVOT (MAX(Fee) FOR Branch IN ([0], [1])) P CROSS APPLY (SELECT CAST(P.[0] AS bit) AS Bit) x

SELECT AI_GENERATE_EMBEDDINGS(N'x' USE MODEL LibModel)

SELECT c.CopyNo, AI_GENERATE_EMBEDDINGS(c.Title USE MODEL LibModel PARAMETERS @Options) FROM dbo.Copy AS c

SELECT c.chunk FROM dbo.Copy AS d CROSS APPLY AI_GENERATE_CHUNKS(SOURCE = d.Title, CHUNK_TYPE = FIXED, CHUNK_SIZE = 50, OVERLAP = 10) AS c

ALTER SERVER CONFIGURATION SET PROCESS AFFINITY CPU = AUTO

ALTER SERVER CONFIGURATION SET PROCESS AFFINITY NUMANODE = 0 TO 1

ALTER SERVER CONFIGURATION SET DIAGNOSTICS LOG ON

ALTER SERVER CONFIGURATION SET DIAGNOSTICS LOG MAX_SIZE = 10 MB

ALTER SERVER CONFIGURATION SET DIAGNOSTICS LOG PATH = DEFAULT

ALTER SERVER CONFIGURATION SET DIAGNOSTICS LOG MAX_FILES = DEFAULT

ALTER SERVER CONFIGURATION SET FAILOVER CLUSTER PROPERTY VerboseLogging = DEFAULT

ALTER SERVER CONFIGURATION SET HADR CLUSTER CONTEXT = LOCAL

ALTER SERVER CONFIGURATION SET BUFFER POOL EXTENSION ON (FILENAME = 'x', SIZE = 50 GB)

ALTER SERVER CONFIGURATION SET BUFFER POOL EXTENSION ON (FILENAME = 'x', SIZE = 50 MB)

ALTER SERVER CONFIGURATION SET BUFFER POOL EXTENSION OFF

ALTER SERVER CONFIGURATION SET SOFTNUMA OFF

CREATE RESOURCE POOL LibPool WITH (MIN_CPU_PERCENT = 10, AFFINITY SCHEDULER = AUTO)

ALTER RESOURCE POOL LibPool WITH (AFFINITY NUMANODE = (0))

CREATE EXTERNAL RESOURCE POOL LibExtPool WITH (MAX_CPU_PERCENT = 75, AFFINITY CPU = AUTO)

ALTER EXTERNAL RESOURCE POOL LibExtPool WITH (AFFINITY CPU = AUTO)

ALTER DATABASE Lib SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)

ALTER DATABASE Lib SET TARGET_RECOVERY_TIME = 60 MINUTES

ALTER DATABASE Lib SET TARGET_RECOVERY_TIME = 90 SECONDS

ALTER DATABASE Lib SET CHANGE_TRACKING (CHANGE_RETENTION = 30 MINUTES)

ALTER DATABASE Lib SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON)

ALTER TABLE dbo.Loan ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON)

ALTER INDEX IX_Copy ON dbo.Copy RESUME WITH (MAXDOP = 2, MAX_DURATION = 5 MINUTES)

ALTER INDEX IX_Copy ON dbo.Copy REBUILD WITH (ONLINE = ON, RESUMABLE = ON, MAX_DURATION = 5 MINUTES)

CREATE INDEX IX_Copy ON dbo.Copy (CopyNo) WITH (ONLINE = ON, RESUMABLE = ON, MAX_DURATION = 5 MINUTES)

CREATE INDEX IX_Copy ON dbo.Copy (CopyNo) WITH (ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 1 MINUTES, ABORT_AFTER_WAIT = NONE)), RESUMABLE = ON, MAX_DURATION = 5 MINUTES)

CREATE CLUSTERED COLUMNSTORE INDEX CCI_Copy ON dbo.Copy WITH (COMPRESSION_DELAY = 10 MINUTES)

CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_Copy ON dbo.Copy (CopyNo) WITH (COMPRESSION_DELAY = 10 MINUTES)

ALTER INDEX IX_Copy ON dbo.Copy SET (COMPRESSION_DELAY = 10 MINUTES)

CREATE TABLE dbo.Loan2 (LoanId int, INDEX CCI_Loan2 CLUSTERED COLUMNSTORE WITH (COMPRESSION_DELAY = 10 MINUTES))

ALTER TABLE dbo.Loan ADD CONSTRAINT UQ_Loan UNIQUE (LoanId) WITH (ONLINE = ON, RESUMABLE = ON, MAX_DURATION = 5 MINUTES)

CREATE DATABASE Lib ON PRIMARY (NAME = 'Lib', FILENAME = 'x.mdf', SIZE = 10 MB, MAXSIZE = UNLIMITED, FILEGROWTH = 10 %), (NAME = Lib2, FILENAME = 'y.ndf', SIZE = 5 MB, MAXSIZE = 50 MB), FILEGROUP LibFg (NAME = Lib3, FILENAME = 'z.ndf') LOG ON (NAME = LibLog, FILENAME = 'w.ldf', SIZE = 5 MB, MAXSIZE = 25 MB, FILEGROWTH = 5 MB)

CREATE DATABASE Lib ON PRIMARY (NAME = Lib, FILENAME = 'x'), FILEGROUP LibFs CONTAINS FILESTREAM DEFAULT (NAME = LibFs, FILENAME = 'y', MAXSIZE = UNLIMITED), (NAME = LibFs2, FILENAME = 'z', MAXSIZE = 10 GB)

ALTER DATABASE Lib ADD FILE (NAME = Lib3, FILENAME = 'x', SIZE = 5 MB, MAXSIZE = 100 MB, FILEGROWTH = 5 MB), (NAME = Lib4, FILENAME = 'y') TO FILEGROUP LibFg

ALTER DATABASE Lib ADD LOG FILE (NAME = LibLog2, FILENAME = 'x', SIZE = 5 MB)

ALTER DATABASE Lib MODIFY FILE (NAME = Lib3, SIZE = 20 MB, MAXSIZE = 100 MB)

ALTER DATABASE Lib MODIFY (EDITION = 'Standard', MAXSIZE = 250 GB)

ALTER DATABASE Lib SET SINGLE_USER WITH ROLLBACK AFTER 10 SECONDS

ALTER DATABASE Lib SET READ_ONLY, RESTRICTED_USER WITH ROLLBACK IMMEDIATE

ALTER DATABASE Lib SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT

ALTER DATABASE Lib MODIFY FILEGROUP LibFg READ_WRITE

ALTER DATABASE Lib MODIFY FILEGROUP LibFg AUTOGROW_ALL_FILES

ALTER DATABASE Lib ADD FILEGROUP LibFs CONTAINS FILESTREAM

ALTER DATABASE Lib SET AUTOMATIC_TUNING (CREATE_INDEX = ON, DROP_INDEX = DEFAULT)

ALTER DATABASE Lib SET FILESTREAM (NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = 'Lib')

CREATE DATABASE Lib WITH LEDGER = ON

CREATE DATABASE Lib ON (NAME = Lib, FILENAME = 'x') LOG ON (NAME = LibLog, FILENAME = 'y') WITH TRUSTWORTHY ON, FILESTREAM (NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = 'Lib')

ALTER AVAILABILITY GROUP LibAg ADD REPLICA ON 'LIBSRV2' WITH (ENDPOINT_URL = 'TCP://x:5022', AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, FAILOVER_MODE = AUTOMATIC),
'LIBSRV3' WITH (ENDPOINT_URL = 'TCP://y:5022', AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT, FAILOVER_MODE = MANUAL, SECONDARY_ROLE (ALLOW_CONNECTIONS = NO))

CREATE DATABASE Lib2 (EDITION = 'Standard', MAXSIZE = 250 GB)

CREATE DATABASE LibCloud COLLATE Latin1_General_CI_AS (EDITION = 'Standard', MAXSIZE = 250 GB)

SET LANGUAGE 'us_english', DATEFORMAT dmy

SET NOCOUNT, XACT_ABORT ON

CREATE PROCEDURE dbo.LibNative WITH NATIVE_COMPILATION, SCHEMABINDING AS BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'us_english', DATEFIRST = 7, DATEFORMAT = 'dmy', DELAYED_DURABILITY = ON) SELECT 1 END

CREATE DATABASE Lib CONTAINMENT = NONE ON PRIMARY (NAME = Lib, FILENAME = 'x'), FILEGROUP LibFs CONTAINS FILESTREAM DEFAULT (NAME = LibFs, FILENAME = 'y', MAXSIZE = UNLIMITED), (NAME = LibFs2, FILENAME = 'z', MAXSIZE = 10 GB) LOG ON (NAME = LibLog, FILENAME = 'w')

CREATE INDEX IX_Copy ON dbo.Copy (CopyNo) WITH (DATA_COMPRESSION = ROW)

CREATE INDEX IX_Copy ON dbo.Copy (CopyNo) INCLUDE (BranchId) WHERE CopyNo IS NOT NULL WITH (MAXDOP = 1, DATA_COMPRESSION = PAGE)

ALTER INDEX IX_Copy ON dbo.Copy REBUILD WITH (MAXDOP = 1, DATA_COMPRESSION = PAGE)

ALTER INDEX IX_Copy ON dbo.Copy REBUILD PARTITION = ALL WITH (DATA_COMPRESSION = ROW ON PARTITIONS (1), DATA_COMPRESSION = PAGE ON PARTITIONS (2 TO 4))

ALTER TABLE dbo.Copy REBUILD WITH (MAXDOP = 1, DATA_COMPRESSION = COLUMNSTORE)

ALTER TABLE dbo.Copy REBUILD PARTITION = 1 WITH (DATA_COMPRESSION = NONE)

CREATE CLUSTERED COLUMNSTORE INDEX CCI_Copy ON dbo.Copy WITH (DROP_EXISTING = ON, DATA_COMPRESSION = COLUMNSTORE_ARCHIVE)

CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_Copy ON dbo.Copy (CopyNo) WITH (DATA_COMPRESSION = COLUMNSTORE)

CREATE TABLE dbo.Loan2 (LoanId int, Note xml) WITH (XML_COMPRESSION = ON, DATA_COMPRESSION = ROW)

ALTER TABLE dbo.Copy ADD CONSTRAINT PK_Copy PRIMARY KEY CLUSTERED (CopyNo) WITH (DATA_COMPRESSION = PAGE)

CREATE PARTITION FUNCTION LibRange (int) AS RANGE LEFT FOR VALUES (1, 100)

CREATE PARTITION FUNCTION LibRange (int) AS RANGE RIGHT FOR VALUES (1, 100)

ALTER PARTITION FUNCTION LibRange () SPLIT RANGE (500)

ALTER PARTITION FUNCTION LibRange () MERGE RANGE (100)

CREATE PARTITION SCHEME LibScheme AS PARTITION LibRange ALL TO ([PRIMARY])

CREATE EXTERNAL LIBRARY LibPackage FROM (CONTENT = 'C:\x.zip', PLATFORM = WINDOWS) WITH (LANGUAGE = 'R')

CREATE EXTERNAL LIBRARY LibPackage AUTHORIZATION dbo FROM (CONTENT = 0x01), (CONTENT = 'y.tar.gz', PLATFORM = LINUX) WITH (LANGUAGE = 'Python')

ALTER EXTERNAL LIBRARY LibPackage SET (CONTENT = 'C:\x.zip', PLATFORM = WINDOWS) WITH (LANGUAGE = 'R')

CREATE COLUMN MASTER KEY LibMasterKey WITH (KEY_STORE_PROVIDER_NAME = 'MSSQL_CERTIFICATE_STORE', KEY_PATH = 'x')

CREATE COLUMN ENCRYPTION KEY LibKey WITH VALUES (COLUMN_MASTER_KEY = LibMasterKey, ALGORITHM = 'RSA_OAEP', ENCRYPTED_VALUE = 0x01)

ALTER COLUMN ENCRYPTION KEY LibKey ADD VALUE (COLUMN_MASTER_KEY = LibMasterKey, ALGORITHM = 'RSA_OAEP', ENCRYPTED_VALUE = 0x01)

ALTER TABLE dbo.Lib_Reader ALTER COLUMN ReaderName nvarchar(50) COLLATE Latin1_General_BIN2 ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = LibKey, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')

CREATE TABLE dbo.Lib_Reader2 (ReaderName nvarchar(50) COLLATE Latin1_General_BIN2 ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = LibKey, ENCRYPTION_TYPE = RANDOMIZED, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL)

ALTER EXTERNAL LIBRARY LibPackage
SET (CONTENT = 0x01, PLATFORM = WINDOWS)
WITH (LANGUAGE = 'R')

ALTER EXTERNAL LIBRARY LibPackage AUTHORIZATION dbo SET (CONTENT = 0x01, PLATFORM = LINUX) WITH (LANGUAGE = 'R')

GRANT EXECUTE ON EXTERNAL MODEL::LibModel TO LibRole

DENY EXECUTE ON EXTERNAL MODEL::LibModel TO LibRole

REVOKE EXECUTE ON EXTERNAL MODEL::LibModel FROM LibRole CASCADE

GRANT ALTER ON SEARCH PROPERTY LIST::LibProperties TO LibRole

GRANT REFERENCES ON XML SCHEMA COLLECTION::dbo.LibSchemas TO LibRole

GRANT ALTER ON SYMMETRIC KEY::LibKey TO LibRole

GRANT REFERENCES ON ASYMMETRIC KEY::LibKey TO LibRole

GRANT REFERENCES ON MESSAGE TYPE::LibMessage TO LibRole

GRANT ALTER ON REMOTE SERVICE BINDING::LibBinding TO LibRole

GRANT REFERENCES ON FULLTEXT CATALOG::LibCatalog TO LibRole

GRANT ALTER ON FULLTEXT STOPLIST::LibStoplist TO LibRole

GRANT ALTER ON APPLICATION ROLE::LibAppRole TO LibRole

GRANT ALTER ON AVAILABILITY GROUP::LibGroup TO LibLogin

GRANT ALTER ON SERVER ROLE::LibServerRole TO LibLogin

ALTER AUTHORIZATION ON EXTERNAL MODEL::LibModel TO dbo

ALTER AUTHORIZATION ON DATABASE::LibDb TO LibLogin

ALTER AUTHORIZATION ON SCHEMA::Lib TO SCHEMA OWNER

ALTER AUTHORIZATION ON OBJECT::dbo.Loan TO LibUser

ALTER AUTHORIZATION ON dbo.Loan TO LibUser

ALTER AUTHORIZATION ON SEARCH PROPERTY LIST::LibProperties TO dbo

ALTER AUTHORIZATION ON XML SCHEMA COLLECTION::dbo.LibSchemas TO dbo

ALTER AUTHORIZATION ON AVAILABILITY GROUP::LibGroup TO LibLogin

ALTER AUTHORIZATION ON ENDPOINT::LibEndpoint TO LibLogin

CREATE FULLTEXT INDEX ON dbo.Copy (Title) KEY INDEX PK_Copy WITH SEARCH PROPERTY LIST = LibProperties

CREATE FULLTEXT INDEX ON dbo.Copy (Title) KEY INDEX PK_Copy WITH (CHANGE_TRACKING = AUTO, SEARCH PROPERTY LIST = LibProperties)

ALTER FULLTEXT INDEX ON dbo.Copy SET SEARCH PROPERTY LIST LibProperties

ALTER FULLTEXT INDEX ON dbo.Copy SET SEARCH PROPERTY LIST OFF

ALTER CREDENTIAL LibCredential WITH IDENTITY = 'x', SECRET = 'y'

CREATE DATABASE SCOPED CREDENTIAL LibCredential WITH IDENTITY = 'x', SECRET = 'y'

ALTER DATABASE SCOPED CREDENTIAL LibCredential WITH IDENTITY = 'x', SECRET = 'y'

CREATE CREDENTIAL LibCredential -- 帳號
WITH IDENTITY = 'x' -- 密碼
, SECRET = 'y'

CREATE LOGIN [reader@library.org] FROM EXTERNAL PROVIDER

CREATE USER [reader@library.org] FROM EXTERNAL PROVIDER

CREATE USER LibUser FROM EXTERNAL PROVIDER WITH OBJECT_ID = 'x'

CREATE WORKLOAD GROUP LibGroup WITH (IMPORTANCE = HIGH)

CREATE WORKLOAD GROUP LibGroup WITH (REQUEST_MAX_MEMORY_GRANT_PERCENT = 25, IMPORTANCE = LOW, MAX_DOP = 4) USING LibPool

ALTER WORKLOAD GROUP LibGroup WITH (GROUP_MAX_REQUESTS = 10, IMPORTANCE = MEDIUM)

CREATE SPATIAL INDEX SI_Branch ON dbo.Branch (GeoPoint) WITH (GRIDS = (LEVEL_1 = HIGH, LEVEL_2 = LOW, LEVEL_3 = MEDIUM, LEVEL_4 = LOW))

CREATE SPATIAL INDEX SI_Branch ON dbo.Branch (GeoPoint) USING GEOMETRY_GRID WITH (BOUNDING_BOX = (0, 0, 100, 100), GRIDS = (LEVEL_1 = HIGH))

CREATE SPATIAL INDEX SI_Branch ON dbo.Branch (GeoPoint) WITH (GRIDS = (HIGH, LOW, MEDIUM, LOW))

CREATE DATABASE AUDIT SPECIFICATION LibDbAuditSpec FOR SERVER AUDIT LibAudit ADD (SELECT ON dbo.Loan BY LibRole)

CREATE DATABASE AUDIT SPECIFICATION LibDbAuditSpec FOR SERVER AUDIT LibAudit ADD (SELECT, INSERT ON OBJECT::dbo.Loan BY dbo, LibRole) WITH (STATE = ON)

ALTER DATABASE AUDIT SPECIFICATION LibDbAuditSpec ADD (EXECUTE ON SCHEMA::dbo BY LibRole), DROP (DELETE ON dbo.Loan BY LibRole)

ALTER SECURITY POLICY dbo.LibPolicy ADD FILTER PREDICATE dbo.fn_LoanFilter(ReaderId) ON dbo.Copy

ALTER SECURITY POLICY dbo.LibPolicy ALTER FILTER PREDICATE dbo.fn_LoanFilter(ReaderId) ON dbo.Loan

ALTER SECURITY POLICY dbo.LibPolicy DROP FILTER PREDICATE ON dbo.Loan

ALTER SECURITY POLICY dbo.LibPolicy ADD BLOCK PREDICATE dbo.fn_LoanFilter(ReaderId) ON dbo.Loan AFTER INSERT, DROP BLOCK PREDICATE ON dbo.Copy BEFORE UPDATE

ALTER SECURITY POLICY dbo.LibPolicy ALTER BLOCK PREDICATE dbo.fn_LoanFilter(ReaderId) ON dbo.Loan AFTER UPDATE

CREATE CREDENTIAL LibCredential WITH IDENTITY = 'x'
CREATE CREDENTIAL LibCredential WITH IDENTITY = 'x', SECRET = 'y'

SELECT BranchId, SUM(Fee) OVER ByBranch AS Total, AVG(Fee) OVER (ByDate ROWS UNBOUNDED PRECEDING) AS Running
FROM dbo.Loan
WHERE Fee > 0
WINDOW ByBranch AS (PARTITION BY BranchId), ByDate AS (ByBranch ORDER BY LoanDate)
ORDER BY BranchId

SELECT BranchId, COUNT(*) OVER ByBranch FROM dbo.Loan GROUP BY BranchId HAVING COUNT(*) > 1 WINDOW ByBranch AS (ORDER BY BranchId DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)

SELECT SUM(Fee) OVER ByCopy FROM dbo.Loan WINDOW ByCopy AS (PARTITION BY CopyNo, ReaderId ORDER BY LoanDate RANGE UNBOUNDED PRECEDING) ORDER BY SUM(Fee) OVER ByCopy

SELECT ROUND(Fee, 2) AS Fee, ROW_NUMBER() OVER (ORDER BY Fee) FROM dbo.Loan ORDER BY Fee

DECLARE @Code NVARCHAR(10) = N'x', @Seq INT = 1; DECLARE @Name NVARCHAR(10) = @Code COLLATE Latin1_General_CI_AS, @Next INT = COALESCE(@Seq, 0)

SELECT JSON_OBJECT('Copy': CopyNo, 'Due': DueDate NULL ON NULL RETURNING JSON), JSON_ARRAY(CopyNo, Fee * 2 ABSENT ON NULL), JSON_OBJECT(ABSENT ON NULL) FROM dbo.Loan

SELECT JSON_ARRAYAGG(CopyNo ORDER BY DueDate NULL ON NULL RETURNING JSON), JSON_OBJECTAGG(CopyNo: Fee ABSENT ON NULL) FROM dbo.Loan

SELECT DATE_BUCKET(WEEK, 1, DueDate), LAG(Fee) IGNORE NULLS OVER (ORDER BY DueDate), FIRST_VALUE(Fee) RESPECT NULLS OVER (ORDER BY DueDate ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING) FROM dbo.Loan

SELECT IDENTITY(INT, 1, 1) AS RowNo, TRIM('0' FROM CopyNo) AS Copy2, {fn CURRENT_TIME} AS Now2 INTO #Copies FROM dbo.Loan FOR SYSTEM_TIME BETWEEN '2026-01-01' AND '2026-02-01'

DECLARE @Model VARBINARY(MAX); SELECT d.CopyNo, p.Score FROM PREDICT(MODEL = @Model, DATA = dbo.Copy AS d, RUNTIME = ONNX) WITH (Score FLOAT) AS p

DECLARE @Skip INT = 1, @Take INT = 5; SELECT CopyNo FROM dbo.Copy ORDER BY CopyNo OFFSET @Skip - 1 ROWS FETCH NEXT @Take - @Skip + 1 ROWS ONLY

SELECT CopyNo FROM dbo.Copy ORDER BY CopyNo
FETCH APPROXIMATE FIRST 5 ROWS ONLY

CREATE TABLE dbo.Lib_Reader (ReaderId INT, Name NVARCHAR(50)) AS NODE

CREATE TABLE dbo.Loan (LoanDate DATE, CONSTRAINT EC_Loan CONNECTION (dbo.Lib_Reader TO dbo.Copy, dbo.Copy TO dbo.Branch) ON DELETE CASCADE, CONNECTION (dbo.Branch TO dbo.Lib_Reader)) AS EDGE

CREATE TABLE dbo.LoanDetail (CONNECTION (dbo.Copy TO dbo.Branch) ON DELETE NO ACTION, CONSTRAINT EC_Return CONNECTION (dbo.Branch TO dbo.Copy)) AS EDGE

CREATE TABLE dbo.Lib_Tag AS EDGE

ALTER TABLE dbo.Loan ADD CONSTRAINT EC_Copy CONNECTION (dbo.Copy TO dbo.Lib_Reader)

SELECT r.ReaderId, STRING_AGG(c.CopyNo, '->') WITHIN GROUP (GRAPH PATH) AS Copies, LAST_VALUE(c.CopyNo) WITHIN GROUP (GRAPH PATH) AS LastCopy
FROM dbo.Lib_Reader AS r, dbo.Loan FOR PATH AS l, dbo.Copy FOR PATH c, dbo.Branch AS b, dbo.LoanDetail AS m
WHERE MATCH(SHORTEST_PATH(r(-(l)->c)+) AND LAST_NODE(c)-(m)->b)

SELECT r.ReaderId FROM dbo.Lib_Reader AS r, dbo.Loan AS l, dbo.Copy AS c, dbo.LoanDetail AS m, dbo.Branch AS b WHERE MATCH(r-(l)->c AND b<-(m)-c)

CREATE TABLE dbo.Shelf (Code char(10) COLLATE Latin1_General_CI_AS SPARSE NULL, Fee int MASKED WITH (FUNCTION = 'default()') HIDDEN NOT NULL, Neg AS -Fee PERSISTED NOT NULL, ShelfNo int IDENTITY(1, 1) NOT FOR REPLICATION CONSTRAINT PkShelf PRIMARY KEY, Kind int CONSTRAINT UqKind UNIQUE WITH FILLFACTOR = 80 ON [PRIMARY], Title NATIONAL CHARACTER VARYING(40) NULL, Doc varbinary(max) FILESTREAM NULL, Props xml COLUMN_SET FOR ALL_SPARSE_COLUMNS)

ALTER TABLE dbo.Shelf ADD Note CHAR VARYING(20) SPARSE NULL, Rate DOUBLE PRECISION NULL

ALTER TABLE dbo.Shelf ALTER COLUMN Title nvarchar(40) MASKED WITH (FUNCTION = 'partial(1, "x", 0)') NULL

DECLARE @Shelf AS TABLE (Code int SPARSE NULL, Title NATIONAL CHAR(10) NOT NULL)

SELECT * FROM OPENJSON(@Doc) WITH (Code nvarchar(10) COLLATE Latin1_General_CI_AS '$.code', Tags nvarchar(max) '$.tags' AS JSON)

CREATE XML INDEX XIX_Copy ON dbo.Copy (Note) USING XML INDEX PXIX_Copy FOR PATH

CREATE SELECTIVE XML INDEX SXIX_Copy ON dbo.Copy (Note) WITH XMLNAMESPACES ('urn:lib' AS Lib) FOR (BookTitle = '/Lib:book/Lib:title' AS SQL nvarchar(40), BookYear = '/Lib:book/Lib:year' AS XQUERY 'xs:double' SINGLETON)

CREATE JSON INDEX JIX_Copy ON dbo.Copy (Doc) FOR ('$.title') WITH (FILLFACTOR = 80)

CREATE TYPE dbo.CopyList AS TABLE (CopyNo int NOT NULL PRIMARY KEY NONCLUSTERED) WITH (MEMORY_OPTIMIZED = ON)

CREATE TABLE dbo.Shelf (ShelfNo int, Code int, INDEX IX_Shelf UNIQUE NONCLUSTERED (ShelfNo) INCLUDE (Code) WHERE Code > 0 WITH (FILLFACTOR = 80))

ALTER TABLE dbo.Shelf ALTER INDEX IX_Shelf REBUILD WITH (BUCKET_COUNT = 64)

CREATE INDEX IX_Copy ON dbo.Copy (CopyNo) WITH (XML_COMPRESSION = ON ON PARTITIONS (1 TO 2))

CREATE FULLTEXT INDEX ON dbo.Copy (Title TYPE COLUMN Ext LANGUAGE 1033, Summary LANGUAGE 1028 STATISTICAL_SEMANTICS) KEY INDEX PK_Copy

ALTER FULLTEXT INDEX ON dbo.Copy ADD (Title, Summary TYPE COLUMN Ext) WITH NO POPULATION

ALTER FULLTEXT CATALOG CopyCatalog REBUILD WITH ACCENT_SENSITIVITY = ON

ALTER FULLTEXT STOPLIST CopyStoplist ADD 'the' LANGUAGE 1033;

ALTER FULLTEXT STOPLIST CopyStoplist DROP ALL LANGUAGE 1033;

CREATE FULLTEXT STOPLIST CopyStoplist FROM SYSTEM STOPLIST AUTHORIZATION dbo;

CREATE FULLTEXT CATALOG CopyCatalog WITH ACCENT_SENSITIVITY = OFF AS DEFAULT

CREATE FULLTEXT CATALOG CopyCatalog ON FILEGROUP LibFs IN PATH 'x' WITH ACCENT_SENSITIVITY = ON

SELECT CopyNo FROM dbo.Copy WHERE CONTAINS(PROPERTY(Title, 'Author'), 'x')

SELECT c.CopyNo FROM dbo.Copy AS c INNER JOIN CONTAINSTABLE(dbo.Copy, (Title, Summary), 'book', LANGUAGE 1033, 10) AS k ON c.CopyNo = k.[KEY] WHERE FREETEXT(c.Title, 'book', LANGUAGE 1033)

CREATE TABLE dbo.Shelf (ShelfNo int NOT NULL PRIMARY KEY NONCLUSTERED HASH WITH (BUCKET_COUNT = 64))

CREATE TABLE dbo.Shelf (ShelfNo int NOT NULL, PRIMARY KEY NONCLUSTERED HASH (ShelfNo) WITH (BUCKET_COUNT = 64))

CREATE TYPE dbo.CopyList AS TABLE (CopyNo int NOT NULL PRIMARY KEY NONCLUSTERED HASH WITH (BUCKET_COUNT = 64)) WITH (MEMORY_OPTIMIZED = ON)

GRANT CREATE TABLE, VIEW DEFINITION, ALTER ANY USER TO LibRole

GRANT CONTROL SERVER, VIEW SERVER STATE TO LibLogin

DENY VIEW DEFINITION ON SCHEMA::dbo TO LibRole CASCADE

REVOKE SELECT ON dbo.Loan (LoanNo) TO LibRole CASCADE

GRANT UNMASK ON OBJECT::dbo.Loan (LoanNo, CopyNo) TO LibRole

REVOKE GRANT OPTION FOR SELECT ON dbo.Loan FROM LibRole CASCADE

GRANT TAKE OWNERSHIP ON dbo.Loan TO LibRole WITH GRANT OPTION AS dbo

CREATE CREDENTIAL LibVault WITH IDENTITY = 'LibUser', SECRET = 'x' FOR CRYPTOGRAPHIC PROVIDER LibEkm

ADD SIGNATURE TO dbo.usp_Lend BY CERTIFICATE LibCert WITH PASSWORD = 'x'

ADD COUNTER SIGNATURE TO dbo.usp_Lend BY ASYMMETRIC KEY LibKey

DROP SIGNATURE FROM dbo.usp_Lend BY CERTIFICATE LibCert

ADD SENSITIVITY CLASSIFICATION TO dbo.Loan.LoanNo, dbo.Loan.CopyNo WITH (LABEL = 'Internal', INFORMATION_TYPE = 'Id', RANK = LOW)

ALTER DATABASE ENCRYPTION KEY REGENERATE WITH ALGORITHM = AES_256

ALTER DATABASE ENCRYPTION KEY ENCRYPTION BY SERVER CERTIFICATE LibCert

CREATE FUNCTION dbo.fn_Fee (@CopyNo int) RETURNS int AS EXTERNAL NAME LibClr.Fees.Calc

CREATE PROCEDURE dbo.usp_Lend @CopyNo int WITH EXECUTE AS CALLER AS EXTERNAL NAME LibClr.Loans.Lend

CREATE AGGREGATE dbo.Concat (@Text nvarchar(4000)) RETURNS nvarchar(4000) EXTERNAL NAME LibClr.Concat

CREATE TYPE dbo.LibPoint EXTERNAL NAME LibClr.[Lib.Point]

DROP ASSEMBLY LibClr WITH NO DEPENDENTS

CREATE EXTERNAL LANGUAGE LibJava FROM (CONTENT = 'x.zip', FILE_NAME = 'x.dll', PLATFORM = WINDOWS)

ALTER EXTERNAL LANGUAGE LibJava SET (CONTENT = 'x.zip', FILE_NAME = 'x.dll')

ALTER EXTERNAL LANGUAGE LibJava REMOVE PLATFORM LINUX

ALTER EXTERNAL LANGUAGE LibJava
AUTHORIZATION dbo
REMOVE PLATFORM WINDOWS

ALTER FULLTEXT INDEX ON dbo.Copy ALTER COLUMN Title ADD STATISTICAL_SEMANTICS WITH NO POPULATION

ALTER FULLTEXT INDEX ON dbo.Copy ALTER COLUMN Title DROP STATISTICAL_SEMANTICS

RESTORE DATABASE Lib FROM @Device WITH REPLACE, FILESTREAM (DIRECTORY_NAME = 'LibFs')

CREATE TABLE dbo.Shelf
(
    Code int NOT NULL PRIMARY KEY NONCLUSTERED,
    BranchId int NOT NULL,
    INDEX IX_Shelf HASH (BranchId) WITH (BUCKET_COUNT = 1024),
    INDEX IX_Shelf2 UNIQUE NONCLUSTERED (BranchId)
) WITH (MEMORY_OPTIMIZED = ON)

ALTER FULLTEXT INDEX ON dbo.Copy SET STOPLIST = SYSTEM WITH NO POPULATION

ALTER SERVICE LibService ON QUEUE dbo.LibQueue (ADD CONTRACT LibContract, DROP CONTRACT LibOldContract)

ALTER SERVICE LibService (DROP CONTRACT LibOldContract)

CREATE ROUTE LibRoute WITH SERVICE_NAME = 'LibService', BROKER_INSTANCE = 'x', LIFETIME = 60, ADDRESS = 'TCP://lib:4022', MIRROR_ADDRESS = 'TCP://lib2:4022'

ALTER ROUTE LibRoute WITH SERVICE_NAME = 'LibService', LIFETIME = 60

ALTER QUEUE dbo.LibQueue WITH ACTIVATION (DROP)

ALTER REMOTE SERVICE BINDING LibBinding WITH USER = LibUser, ANONYMOUS = ON

CREATE REMOTE SERVICE BINDING LibBinding TO SERVICE 'LibService' WITH USER = LibUser, ANONYMOUS = OFF

SELECT c.CopyNo FROM dbo.Copy c INNER REMOTE JOIN dbo.Loan l ON l.CopyNo = c.CopyNo LEFT OUTER HASH JOIN dbo.Branch b ON b.BranchId = c.BranchId

SELECT c.CopyNo FROM dbo.Copy c INNER MERGE JOIN dbo.Loan l ON l.CopyNo = c.CopyNo FULL LOOP JOIN dbo.Branch b ON b.BranchId = c.BranchId

SELECT BranchId, CopyNo, COUNT(*) FROM dbo.Copy GROUP BY CUBE (BranchId), ROLLUP (CopyNo), GROUPING SETS ((BranchId), ())

SELECT CopyNo FROM dbo.Copy WHERE BranchId IS NOT DISTINCT FROM NULL

SELECT CASE WHEN BranchId IS NOT DISTINCT FROM NULL THEN 0 END FROM dbo.Copy

SELECT * FROM OPENROWSET(BULK 'Copy.txt', FORMATFILE = 'Copy.fmt', ORDER (CopyNo ASC, BranchId DESC)) AS c

WITH XMLNAMESPACES ('urn:lib' AS Lib) SELECT CopyNo FROM dbo.Copy FOR XML PATH

CREATE WORKLOAD GROUP LibGroup WITH (IMPORTANCE = HIGH) USING LibPool, EXTERNAL LibExternalPool

ALTER WORKLOAD GROUP LibGroup USING EXTERNAL LibExternalPool

DROP SYMMETRIC KEY LibKey REMOVE PROVIDER KEY

DROP ASYMMETRIC KEY LibKey REMOVE PROVIDER KEY

DENY SELECT ON EXTERNAL MODEL::LibModel TO LibUser, LibReader
CASCADE

ALTER INDEX IX_Copy ON dbo.Copy REORGANIZE PARTITION = 1 WITH (COMPRESS_ALL_ROW_GROUPS = ON)

ALTER TABLE dbo.Copy DROP COLUMN Shelf, CONSTRAINT PK_Copy WITH (ONLINE = ON), CK_Copy WITH (MOVE TO LibFileGroup)

ALTER EVENT SESSION LibTrace ON DATABASE ADD EVENT sqlserver.lock_acquired

CREATE SYMMETRIC KEY LibEkmKey FROM PROVIDER LibEkm WITH PROVIDER_KEY_NAME = 'x', CREATION_DISPOSITION = CREATE_NEW

CREATE SYMMETRIC KEY LibEkmKey AUTHORIZATION LibUser
FROM PROVIDER LibEkm WITH PROVIDER_KEY_NAME = 'x', CREATION_DISPOSITION = OPEN_EXISTING

CREATE ASYMMETRIC KEY LibEkmAsym FROM PROVIDER LibEkm WITH ALGORITHM = RSA_2048, PROVIDER_KEY_NAME = 'x', CREATION_DISPOSITION = OPEN_EXISTING

ADD COUNTER SIGNATURE TO OBJECT::dbo.usp_Lend BY ASYMMETRIC KEY LibKey

DROP SIGNATURE FROM OBJECT::dbo.usp_Lend BY CERTIFICATE LibCert

ALTER LOGIN LibLogin ADD CREDENTIAL LibVault

ALTER LOGIN LibLogin DROP CREDENTIAL LibVault

ALTER ASSEMBLY LibClr DROP FILE ALL

ALTER ASSEMBLY LibClr WITH PERMISSION_SET = SAFE, VISIBILITY = ON

ALTER DATABASE LibArchive SET DEFAULT_FULLTEXT_LANGUAGE = 1033, TWO_DIGIT_YEAR_CUTOFF = 2000, CONTAINMENT = PARTIAL

CREATE DATABASE LibArchive CONTAINMENT = PARTIAL WITH TRUSTWORTHY ON

CREATE CERTIFICATE LibCert FROM EXECUTABLE FILE = 'x' WITH PRIVATE KEY (FILE = 'x', DECRYPTION BY PASSWORD = 'x')

CREATE CERTIFICATE LibCert AUTHORIZATION LibOwner FROM FILE = 'x' WITH PRIVATE KEY (FILE = 'x', DECRYPTION BY PASSWORD = 'x')

SELECT * FROM OPENROWSET(BULK 'Copy.csv', SINGLE_NCLOB, ORDER (CopyNo ASC, BranchId DESC) UNIQUE) AS c

SELECT * FROM dbo.Copy c WHERE c.CopyNo = 1 OPTION (TABLE HINT (c, FORCESCAN, NOLOCK))

DECLARE @Doc XML = '<a/>'
SELECT Node.Item.query('.') AS Fragment FROM @Doc.nodes('/a') Node(Item)

CREATE PARTITION FUNCTION [LibRange] (DATETIME) AS RANGE RIGHT FOR VALUES ('20200101')

IF 1 = 1
BEGIN
DROP TRIGGER LibTrg ON DATABASE
END

Done:
EXECUTE sp_serveroption 'LibLink', 'rpc out', true

CREATE TABLE dbo.LoanLedger (LoanId INT, StartTx BIGINT GENERATED ALWAYS AS TRANSACTION_ID START HIDDEN NOT NULL, EndTx BIGINT GENERATED ALWAYS AS TRANSACTION_ID END HIDDEN NULL, StartSeq BIGINT GENERATED ALWAYS AS SEQUENCE_NUMBER START HIDDEN NOT NULL, EndSeq BIGINT GENERATED ALWAYS AS SEQUENCE_NUMBER END HIDDEN NULL)

SELECT CopyNo FROM dbo.Copy FOR XML PATH, ELEMENTS ABSENT

SELECT CopyNo FROM dbo.Copy FOR XML RAW, ELEMENTS XSINIL, ROOT('Copies')

ALTER AVAILABILITY GROUP LibGroup REMOVE REPLICA ON 'LibNode2'
