// <auto-generated />
//
// 由 tools/Generate-Keywords.ps1 產生，請勿手動編輯。
// 來源：Microsoft.SqlServer.TransactSql.ScriptDom 18.0.56.2（TSql170Parser）
//
// 關鍵字取自 TSqlTokenType 的成員名稱並以 tokenizer 回驗，
// 另加腳本裡 $NonReservedSupplement 的 11 個非保留字；
// 位置則是把每個關鍵字塞進樣板剖析、依錯誤碼判定得到的。
//
// 保留字是另外探測的一份：把字塞進識別字的洞裡，剖析器拒收的才算，
// 因此它與上面的關鍵字清單互有出入——兩邊都有對方沒有的字。

using System.Collections.Generic;

namespace SqlAssist.Core.Keywords;

/// <summary>產生出來的關鍵字資料；請由 <see cref="SqlKeywordCatalog"/> 取用。</summary>
internal static class SqlKeywordCatalogData
{
    /// <summary>產生這份目錄所用的 ScriptDom 版本。</summary>
    internal const string SourceVersion = "18.0.56.2";

    /// <summary>全部關鍵字，以及各自可以出現的位置。</summary>
    internal static readonly KeyValuePair<string, SqlKeywordPosition>[] Keywords =
    {
        new("ADD", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.AlterTableAction | SqlKeywordPosition.BlockStart),
        new("ALL", SqlKeywordPosition.SelectList | SqlKeywordPosition.OrderByColumn),
        new("ALTER", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.AlterTableAction | SqlKeywordPosition.BlockStart),
        new("AND", SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.CaseArm),
        new("ANY", SqlKeywordPosition.None),
        new("APPLY", SqlKeywordPosition.None),
        new("AS", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail),
        new("ASC", SqlKeywordPosition.OrderByTail),
        new("AUTHORIZATION", SqlKeywordPosition.DdlObject),
        new("BACKUP", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("BEGIN", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("BETWEEN", SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.CaseArm),
        new("BREAK", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("BROWSE", SqlKeywordPosition.None),
        new("BULK", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart | SqlKeywordPosition.InsertTarget),
        new("BY", SqlKeywordPosition.ByAnchor),
        new("CASCADE", SqlKeywordPosition.None),
        new("CASE", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("CATCH", SqlKeywordPosition.BlockStart),
        new("CHECK", SqlKeywordPosition.AlterTableAction | SqlKeywordPosition.AlterTableAdd | SqlKeywordPosition.ColumnDefinition),
        new("CHECKPOINT", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("CLOSE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("CLUSTERED", SqlKeywordPosition.DdlObject),
        new("COALESCE", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("COLLATE", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.CaseArm | SqlKeywordPosition.CaseBody),
        new("COLUMN", SqlKeywordPosition.DdlObject),
        new("COMMIT", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("COMPUTE", SqlKeywordPosition.None),
        new("CONSTRAINT", SqlKeywordPosition.AlterTableAdd | SqlKeywordPosition.ColumnDefinition),
        new("CONTAINS", SqlKeywordPosition.Predicate),
        new("CONTAINSTABLE", SqlKeywordPosition.DataSource),
        new("CONTINUE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("CONVERT", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("CREATE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("CROSS", SqlKeywordPosition.TableSourceTail),
        new("CURRENT", SqlKeywordPosition.Predicate),
        new("CURRENT_DATE", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("CURRENT_TIME", SqlKeywordPosition.None),
        new("CURRENT_TIMESTAMP", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("CURRENT_USER", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("CURSOR", SqlKeywordPosition.None),
        new("DATABASE", SqlKeywordPosition.DdlObject),
        new("DBCC", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("DEALLOCATE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("DECLARE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("DEFAULT", SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.AlterTableAdd | SqlKeywordPosition.DdlObject),
        new("DELETE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("DENY", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("DESC", SqlKeywordPosition.OrderByTail),
        new("DISTINCT", SqlKeywordPosition.SelectList),
        new("DISTRIBUTED", SqlKeywordPosition.BlockStart),
        new("DOUBLE", SqlKeywordPosition.None),
        new("DROP", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.AlterTableAction | SqlKeywordPosition.BlockStart),
        new("ELSE", SqlKeywordPosition.CaseBody),
        new("END", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.CaseBody),
        new("ERRLVL", SqlKeywordPosition.SetTarget),
        new("ESCAPE", SqlKeywordPosition.ExpressionTail),
        new("EXCEPT", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.GroupByTail),
        new("EXEC", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("EXECUTE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("EXISTS", SqlKeywordPosition.Predicate),
        new("EXIT", SqlKeywordPosition.None),
        new("EXTERNAL", SqlKeywordPosition.DdlObject),
        new("FETCH", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("FILE", SqlKeywordPosition.None),
        new("FILLFACTOR", SqlKeywordPosition.None),
        new("FOR", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail),
        new("FOREIGN", SqlKeywordPosition.AlterTableAdd | SqlKeywordPosition.ColumnDefinition),
        new("FREETEXT", SqlKeywordPosition.Predicate),
        new("FREETEXTTABLE", SqlKeywordPosition.DataSource),
        new("FROM", SqlKeywordPosition.SelectListTail),
        new("FULL", SqlKeywordPosition.TableSourceTail),
        new("FUNCTION", SqlKeywordPosition.DdlObject),
        new("GO", SqlKeywordPosition.StatementStart),
        new("GOTO", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("GRANT", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("GROUP", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail),
        new("HAVING", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.GroupByTail),
        new("HOLDLOCK", SqlKeywordPosition.TableSourceTail),
        new("IDENTIFIER", SqlKeywordPosition.None),
        new("IDENTITY", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail),
        new("IDENTITY_INSERT", SqlKeywordPosition.SetTarget),
        new("IF", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.AlterTableColumn | SqlKeywordPosition.BlockStart),
        new("IN", SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.CaseArm),
        new("INDEX", SqlKeywordPosition.AlterTableAdd | SqlKeywordPosition.DdlObject | SqlKeywordPosition.ColumnDefinition),
        new("INNER", SqlKeywordPosition.TableSourceTail),
        new("INSERT", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("INTERSECT", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.GroupByTail),
        new("INTO", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.InsertTarget),
        new("IS", SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.CaseArm),
        new("JOIN", SqlKeywordPosition.TableSourceTail),
        new("KEY", SqlKeywordPosition.None),
        new("KILL", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("LEFT", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("LIKE", SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.CaseArm),
        new("LINENO", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("MERGE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.AlterTableAction | SqlKeywordPosition.BlockStart),
        new("NATIONAL", SqlKeywordPosition.None),
        new("NEXT", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("NOCHECK", SqlKeywordPosition.AlterTableAction),
        new("NOLOCK", SqlKeywordPosition.None),
        new("NONCLUSTERED", SqlKeywordPosition.DdlObject),
        new("NOT", SqlKeywordPosition.Predicate | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.CaseArm),
        new("NULL", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("NULLIF", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("OF", SqlKeywordPosition.None),
        new("OFF", SqlKeywordPosition.SetOptionValue),
        new("OFFSET", SqlKeywordPosition.OrderByTail),
        new("OFFSETS", SqlKeywordPosition.SetTarget),
        new("ON", SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.SetOptionValue),
        new("OPEN", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("OPENDATASOURCE", SqlKeywordPosition.DataSource | SqlKeywordPosition.InsertTarget),
        new("OPENQUERY", SqlKeywordPosition.DataSource | SqlKeywordPosition.InsertTarget),
        new("OPENROWSET", SqlKeywordPosition.DataSource | SqlKeywordPosition.InsertTarget),
        new("OPENXML", SqlKeywordPosition.DataSource),
        new("OPTION", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail),
        new("OR", SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.CaseArm),
        new("ORDER", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.GroupByTail),
        new("OUTER", SqlKeywordPosition.TableSourceTail),
        new("OUTPUT", SqlKeywordPosition.TableSourceTail),
        new("OVER", SqlKeywordPosition.InsertTarget),
        new("PARTITION", SqlKeywordPosition.DdlObject),
        new("PERCENT", SqlKeywordPosition.TopClauseTail),
        new("PIVOT", SqlKeywordPosition.TableSourceTail),
        new("PLAN", SqlKeywordPosition.None),
        new("PRIMARY", SqlKeywordPosition.AlterTableAdd | SqlKeywordPosition.DdlObject | SqlKeywordPosition.ColumnDefinition),
        new("PRINT", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("PROC", SqlKeywordPosition.DdlObject),
        new("PROCEDURE", SqlKeywordPosition.DdlObject),
        new("PUBLIC", SqlKeywordPosition.None),
        new("RAISERROR", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("READ", SqlKeywordPosition.None),
        new("READTEXT", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("RECONFIGURE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("REFERENCES", SqlKeywordPosition.None),
        new("REPLICATION", SqlKeywordPosition.None),
        new("RESTORE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("RESTRICT", SqlKeywordPosition.None),
        new("RETURN", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("REVERT", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("REVOKE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("RIGHT", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("ROLLBACK", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("ROWCOUNT", SqlKeywordPosition.SetTarget),
        new("ROWS", SqlKeywordPosition.OrderByTail),
        new("RULE", SqlKeywordPosition.DdlObject),
        new("SAVE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("SCHEMA", SqlKeywordPosition.DdlObject),
        new("SELECT", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("SEMANTICKEYPHRASETABLE", SqlKeywordPosition.DataSource),
        new("SEMANTICSIMILARITYDETAILSTABLE", SqlKeywordPosition.DataSource),
        new("SEMANTICSIMILARITYTABLE", SqlKeywordPosition.DataSource),
        new("SESSION_USER", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("SET", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.AlterTableAction | SqlKeywordPosition.BlockStart),
        new("SETUSER", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("SHUTDOWN", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("SOME", SqlKeywordPosition.None),
        new("STATISTICS", SqlKeywordPosition.DdlObject | SqlKeywordPosition.SetTarget),
        new("STOPLIST", SqlKeywordPosition.None),
        new("SYSTEM_USER", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("TABLE", SqlKeywordPosition.DdlObject),
        new("TABLESAMPLE", SqlKeywordPosition.TableSourceTail),
        new("TEXTSIZE", SqlKeywordPosition.SetTarget),
        new("THEN", SqlKeywordPosition.CaseArm),
        new("THROW", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("TO", SqlKeywordPosition.TableSourceTail),
        new("TOP", SqlKeywordPosition.SelectList | SqlKeywordPosition.InsertTarget),
        new("TRAN", SqlKeywordPosition.BlockStart | SqlKeywordPosition.SetTarget),
        new("TRANSACTION", SqlKeywordPosition.BlockStart | SqlKeywordPosition.SetTarget),
        new("TRIGGER", SqlKeywordPosition.DdlObject),
        new("TRUNCATE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("TRY", SqlKeywordPosition.BlockStart),
        new("TRY_CONVERT", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn),
        new("TSEQUAL", SqlKeywordPosition.Predicate),
        new("UNION", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.GroupByTail),
        new("UNIQUE", SqlKeywordPosition.AlterTableAdd | SqlKeywordPosition.DdlObject | SqlKeywordPosition.ColumnDefinition),
        new("UNPIVOT", SqlKeywordPosition.TableSourceTail),
        new("UPDATE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("UPDATETEXT", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("USE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("USER", SqlKeywordPosition.SelectList | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.Predicate | SqlKeywordPosition.OrderByColumn | SqlKeywordPosition.DdlObject),
        new("USING", SqlKeywordPosition.TableSourceTail),
        new("VALUES", SqlKeywordPosition.TableSourceTail),
        new("VARYING", SqlKeywordPosition.None),
        new("VIEW", SqlKeywordPosition.DdlObject),
        new("WAITFOR", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("WHEN", SqlKeywordPosition.CaseBody),
        new("WHERE", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail),
        new("WHILE", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
        new("WITH", SqlKeywordPosition.StatementStart | SqlKeywordPosition.TopClauseTail | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.AlterTableAction | SqlKeywordPosition.BlockStart),
        new("WRITETEXT", SqlKeywordPosition.StatementStart | SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail | SqlKeywordPosition.BlockStart),
    };

    /// <summary>定位置所用的樣板：每個位置與它的樣板文字。</summary>
    /// <remarks>
    /// 執行期用不到，輸出來是為了讓測試逐條回驗：分析器對樣板文字回報的位置
    /// 必須含那個位置，兩邊說的才是同一個位置。
    /// </remarks>
    internal static readonly KeyValuePair<SqlKeywordPosition, string>[] Templates =
    {
        new(SqlKeywordPosition.StatementStart, ""),
        new(SqlKeywordPosition.StatementStart, "SELECT 1; "),
        new(SqlKeywordPosition.SelectList, "SELECT "),
        new(SqlKeywordPosition.TopClauseTail, "SELECT TOP 10 "),
        new(SqlKeywordPosition.SelectListTail, "SELECT a "),
        new(SqlKeywordPosition.DataSource, "SELECT * FROM "),
        new(SqlKeywordPosition.TableSourceTail, "SELECT * FROM t "),
        new(SqlKeywordPosition.TableSourceTail, "SELECT * FROM t JOIN y "),
        new(SqlKeywordPosition.TableSourceTail, "INSERT INTO t "),
        new(SqlKeywordPosition.TableSourceTail, "GRANT SELECT ON t "),
        new(SqlKeywordPosition.TableSourceTail, "MERGE INTO t "),
        new(SqlKeywordPosition.Predicate, "SELECT * FROM t WHERE "),
        new(SqlKeywordPosition.Predicate, "DELETE FROM t WHERE "),
        new(SqlKeywordPosition.ExpressionTail, "SELECT * FROM t WHERE a = 1 "),
        new(SqlKeywordPosition.ExpressionTail, "SELECT * FROM t WHERE a "),
        new(SqlKeywordPosition.ExpressionTail, "SELECT * FROM t WHERE a LIKE 'x' "),
        new(SqlKeywordPosition.OrderByTail, "SELECT * FROM t ORDER BY a "),
        new(SqlKeywordPosition.OrderByTail, "SELECT * FROM t ORDER BY a OFFSET 10 "),
        new(SqlKeywordPosition.OrderByTail, "SELECT SUM(a) OVER (ORDER BY a "),
        new(SqlKeywordPosition.GroupByTail, "SELECT * FROM t GROUP BY a "),
        new(SqlKeywordPosition.OrderByColumn, "SELECT * FROM t ORDER BY "),
        new(SqlKeywordPosition.OrderByColumn, "SELECT * FROM t GROUP BY "),
        new(SqlKeywordPosition.ByAnchor, "SELECT * FROM t ORDER "),
        new(SqlKeywordPosition.ByAnchor, "SELECT * FROM t GROUP "),
        new(SqlKeywordPosition.AlterTableAction, "ALTER TABLE t "),
        new(SqlKeywordPosition.AlterTableAdd, "ALTER TABLE t ADD "),
        new(SqlKeywordPosition.AlterTableColumn, "ALTER TABLE t ALTER COLUMN "),
        new(SqlKeywordPosition.AlterTableColumn, "ALTER TABLE t DROP COLUMN "),
        new(SqlKeywordPosition.DdlObject, "CREATE "),
        new(SqlKeywordPosition.DdlObject, "ALTER "),
        new(SqlKeywordPosition.DdlObject, "DROP "),
        new(SqlKeywordPosition.CaseArm, "SELECT CASE WHEN a "),
        new(SqlKeywordPosition.CaseArm, "SELECT CASE WHEN a = 1 "),
        new(SqlKeywordPosition.CaseArm, "SELECT CASE a WHEN 1 "),
        new(SqlKeywordPosition.CaseBody, "SELECT CASE WHEN a = 1 THEN 1 "),
        new(SqlKeywordPosition.ColumnDefinition, "CREATE TABLE t ("),
        new(SqlKeywordPosition.ColumnDefinition, "CREATE TABLE t (a int, "),
        new(SqlKeywordPosition.BlockStart, "BEGIN "),
        new(SqlKeywordPosition.BlockStart, "BEGIN TRY SELECT 1 END TRY BEGIN "),
        new(SqlKeywordPosition.SetTarget, "SET "),
        new(SqlKeywordPosition.SetOptionValue, "SET NOCOUNT "),
        new(SqlKeywordPosition.SetOptionValue, "SET IDENTITY_INSERT t "),
        new(SqlKeywordPosition.InsertTarget, "INSERT "),
    };

    /// <summary>不能直接當識別字書寫、插入時一定要加方括號的字。</summary>
    internal static readonly string[] ReservedIdentifiers =
    {
        "ADD", "ALL", "ALTER", "AND", "ANY", "AS", "ASC", "AUTHORIZATION", "BACKUP", "BEGIN",
        "BETWEEN", "BREAK", "BROWSE", "BULK", "BY", "CASCADE", "CASE", "CHECK", "CHECKPOINT",
        "CLOSE", "CLUSTERED", "COALESCE", "COLLATE", "COLUMN", "COMMIT", "COMPUTE",
        "CONSTRAINT", "CONTAINS", "CONTAINSTABLE", "CONTINUE", "CONVERT", "CREATE", "CROSS",
        "CURRENT", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER",
        "CURSOR", "DATABASE", "DBCC", "DEALLOCATE", "DECLARE", "DEFAULT", "DELETE", "DENY",
        "DESC", "DISTINCT", "DISTRIBUTED", "DOUBLE", "DROP", "ELSE", "END", "ERRLVL", "ESCAPE",
        "EXCEPT", "EXEC", "EXECUTE", "EXISTS", "EXIT", "EXTERNAL", "FETCH", "FILE",
        "FILLFACTOR", "FOR", "FOREIGN", "FREETEXT", "FREETEXTTABLE", "FROM", "FULL", "FUNCTION",
        "GOTO", "GRANT", "GROUP", "HAVING", "HOLDLOCK", "IDENTITY", "IDENTITY_INSERT",
        "IDENTITYCOL", "IF", "IN", "INDEX", "INNER", "INSERT", "INTERSECT", "INTO", "IS",
        "JOIN", "KEY", "KILL", "LEFT", "LIKE", "LINENO", "MERGE", "NATIONAL", "NOCHECK",
        "NONCLUSTERED", "NOT", "NULL", "NULLIF", "OF", "OFF", "OFFSETS", "ON", "OPEN",
        "OPENDATASOURCE", "OPENQUERY", "OPENROWSET", "OPENXML", "OPTION", "OR", "ORDER",
        "OUTER", "OVER", "PERCENT", "PIVOT", "PLAN", "PRIMARY", "PRINT", "PROC", "PROCEDURE",
        "PUBLIC", "RAISERROR", "READ", "READTEXT", "RECONFIGURE", "REFERENCES", "REPLICATION",
        "RESTORE", "RESTRICT", "RETURN", "REVERT", "REVOKE", "RIGHT", "ROLLBACK", "ROWCOUNT",
        "ROWGUIDCOL", "RULE", "SAVE", "SCHEMA", "SELECT", "SEMANTICKEYPHRASETABLE",
        "SEMANTICSIMILARITYDETAILSTABLE", "SEMANTICSIMILARITYTABLE", "SESSION_USER", "SET",
        "SETUSER", "SHUTDOWN", "SOME", "STATISTICS", "STOPLIST", "SYSTEM_USER", "TABLE",
        "TABLESAMPLE", "TEXTSIZE", "THEN", "TO", "TOP", "TRAN", "TRANSACTION", "TRIGGER",
        "TRUNCATE", "TRY_CONVERT", "TSEQUAL", "UNION", "UNIQUE", "UNPIVOT", "UPDATE",
        "UPDATETEXT", "USE", "USER", "VALUES", "VARYING", "VIEW", "WAITFOR", "WHEN", "WHERE",
        "WHILE", "WITH", "WRITETEXT",
    };

    /// <summary>子句片語：游標前的尾巴、探測文字、是否封閉、語句到那裡是否已經完整，以及那裡接得上的字。</summary>
    /// <remarks>
    /// 探測文字執行期用不到，輸出來是為了讓測試逐條回驗：片語比對對那段文字
    /// 必須認出同一個片語，兩邊說的才是同一個位置。
    /// </remarks>
    internal static readonly (string Pattern, SqlKeywordPosition After, string Probe, bool Closed, bool EndsStatement, string[] Words)[] ClausePhrases =
    {
        ("SET", SqlKeywordPosition.StatementStart, "SET ", true, false, new string[]
        {
            "ANSI_DEFAULTS", "ANSI_NULL_DFLT_OFF", "ANSI_NULL_DFLT_ON", "ANSI_NULLS",
            "ANSI_PADDING", "ANSI_WARNINGS", "ARITHABORT", "ARITHIGNORE",
            "CONCAT_NULL_YIELDS_NULL", "CONTEXT_INFO", "CURSOR_CLOSE_ON_COMMIT", "DATEFIRST",
            "DATEFORMAT", "DEADLOCK_PRIORITY", "ERRLVL", "FIPS_FLAGGER", "FMTONLY", "FORCEPLAN",
            "IDENTITY_INSERT", "IMPLICIT_TRANSACTIONS", "LANGUAGE", "LOCK_TIMEOUT",
            "NO_BROWSETABLE", "NOCOUNT", "NOEXEC", "NUMERIC_ROUNDABORT", "OFFSETS", "PARSEONLY",
            "QUERY_GOVERNOR_COST_LIMIT", "QUOTED_IDENTIFIER", "REMOTE_PROC_TRANSACTIONS",
            "ROWCOUNT", "SHOWPLAN_ALL", "SHOWPLAN_TEXT", "SHOWPLAN_XML", "STATISTICS",
            "TEXTSIZE", "TRAN", "TRANSACTION", "XACT_ABORT",
        }),
        ("SET ANSI_DEFAULTS", SqlKeywordPosition.StatementStart, "SET ANSI_DEFAULTS ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET ANSI_NULL_DFLT_OFF", SqlKeywordPosition.StatementStart, "SET ANSI_NULL_DFLT_OFF ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET ANSI_NULL_DFLT_ON", SqlKeywordPosition.StatementStart, "SET ANSI_NULL_DFLT_ON ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET ANSI_NULLS", SqlKeywordPosition.StatementStart, "SET ANSI_NULLS ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET ANSI_PADDING", SqlKeywordPosition.StatementStart, "SET ANSI_PADDING ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET ANSI_WARNINGS", SqlKeywordPosition.StatementStart, "SET ANSI_WARNINGS ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET ARITHABORT", SqlKeywordPosition.StatementStart, "SET ARITHABORT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET ARITHIGNORE", SqlKeywordPosition.StatementStart, "SET ARITHIGNORE ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET CONCAT_NULL_YIELDS_NULL", SqlKeywordPosition.StatementStart, "SET CONCAT_NULL_YIELDS_NULL ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET CONTEXT_INFO", SqlKeywordPosition.StatementStart, "SET CONTEXT_INFO ", false, false, new string[]
        {
            "NULL",
        }),
        ("SET CURSOR_CLOSE_ON_COMMIT", SqlKeywordPosition.StatementStart, "SET CURSOR_CLOSE_ON_COMMIT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET DATEFIRST", SqlKeywordPosition.StatementStart, "SET DATEFIRST ", false, false, new string[]
        {
            "NULL",
        }),
        ("SET DATEFORMAT", SqlKeywordPosition.StatementStart, "SET DATEFORMAT ", true, false, new string[]
        {
            "NULL", "mdy", "dmy", "ymd", "ydm", "myd", "dym",
        }),
        ("SET DEADLOCK_PRIORITY", SqlKeywordPosition.StatementStart, "SET DEADLOCK_PRIORITY ", true, false, new string[]
        {
            "NULL", "LOW", "NORMAL", "HIGH",
        }),
        ("SET ERRLVL", SqlKeywordPosition.StatementStart, "SET ERRLVL ", true, false, new string[]
        {
        }),
        ("SET FIPS_FLAGGER", SqlKeywordPosition.StatementStart, "SET FIPS_FLAGGER ", true, false, new string[]
        {
            "OFF",
        }),
        ("SET FMTONLY", SqlKeywordPosition.StatementStart, "SET FMTONLY ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET FORCEPLAN", SqlKeywordPosition.StatementStart, "SET FORCEPLAN ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET IDENTITY_INSERT", SqlKeywordPosition.StatementStart, "SET IDENTITY_INSERT ", false, false, new string[]
        {
        }),
        ("SET IMPLICIT_TRANSACTIONS", SqlKeywordPosition.StatementStart, "SET IMPLICIT_TRANSACTIONS ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET LANGUAGE", SqlKeywordPosition.StatementStart, "SET LANGUAGE ", false, false, new string[]
        {
            "NULL",
        }),
        ("SET LOCK_TIMEOUT", SqlKeywordPosition.StatementStart, "SET LOCK_TIMEOUT ", false, false, new string[]
        {
            "NULL",
        }),
        ("SET NO_BROWSETABLE", SqlKeywordPosition.StatementStart, "SET NO_BROWSETABLE ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET NOCOUNT", SqlKeywordPosition.StatementStart, "SET NOCOUNT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET NOEXEC", SqlKeywordPosition.StatementStart, "SET NOEXEC ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET NUMERIC_ROUNDABORT", SqlKeywordPosition.StatementStart, "SET NUMERIC_ROUNDABORT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET OFFSETS", SqlKeywordPosition.StatementStart, "SET OFFSETS ", true, false, new string[]
        {
            "COMPUTE", "EXEC", "EXECUTE", "FROM", "ORDER", "PARAM", "PROC", "PROCEDURE",
            "SELECT", "STATEMENT", "TABLE",
        }),
        ("SET OFFSETS COMPUTE", SqlKeywordPosition.StatementStart, "SET OFFSETS COMPUTE ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET OFFSETS EXEC", SqlKeywordPosition.StatementStart, "SET OFFSETS EXEC ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET OFFSETS EXECUTE", SqlKeywordPosition.StatementStart, "SET OFFSETS EXECUTE ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET OFFSETS FROM", SqlKeywordPosition.StatementStart, "SET OFFSETS FROM ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET OFFSETS ORDER", SqlKeywordPosition.StatementStart, "SET OFFSETS ORDER ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET OFFSETS PARAM", SqlKeywordPosition.StatementStart, "SET OFFSETS PARAM ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET OFFSETS PROC", SqlKeywordPosition.StatementStart, "SET OFFSETS PROC ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET OFFSETS PROCEDURE", SqlKeywordPosition.StatementStart, "SET OFFSETS PROCEDURE ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET OFFSETS SELECT", SqlKeywordPosition.StatementStart, "SET OFFSETS SELECT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET OFFSETS STATEMENT", SqlKeywordPosition.StatementStart, "SET OFFSETS STATEMENT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET OFFSETS TABLE", SqlKeywordPosition.StatementStart, "SET OFFSETS TABLE ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET PARSEONLY", SqlKeywordPosition.StatementStart, "SET PARSEONLY ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET QUERY_GOVERNOR_COST_LIMIT", SqlKeywordPosition.StatementStart, "SET QUERY_GOVERNOR_COST_LIMIT ", false, false, new string[]
        {
            "NULL",
        }),
        ("SET QUOTED_IDENTIFIER", SqlKeywordPosition.StatementStart, "SET QUOTED_IDENTIFIER ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET REMOTE_PROC_TRANSACTIONS", SqlKeywordPosition.StatementStart, "SET REMOTE_PROC_TRANSACTIONS ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET ROWCOUNT", SqlKeywordPosition.StatementStart, "SET ROWCOUNT ", true, false, new string[]
        {
        }),
        ("SET SHOWPLAN_ALL", SqlKeywordPosition.StatementStart, "SET SHOWPLAN_ALL ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET SHOWPLAN_TEXT", SqlKeywordPosition.StatementStart, "SET SHOWPLAN_TEXT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET SHOWPLAN_XML", SqlKeywordPosition.StatementStart, "SET SHOWPLAN_XML ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET STATISTICS", SqlKeywordPosition.StatementStart, "SET STATISTICS ", true, false, new string[]
        {
            "IO", "PROFILE", "TIME", "XML",
        }),
        ("SET STATISTICS IO", SqlKeywordPosition.StatementStart, "SET STATISTICS IO ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET STATISTICS PROFILE", SqlKeywordPosition.StatementStart, "SET STATISTICS PROFILE ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET STATISTICS TIME", SqlKeywordPosition.StatementStart, "SET STATISTICS TIME ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET STATISTICS XML", SqlKeywordPosition.StatementStart, "SET STATISTICS XML ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET TEXTSIZE", SqlKeywordPosition.StatementStart, "SET TEXTSIZE ", true, false, new string[]
        {
        }),
        ("SET TRAN", SqlKeywordPosition.StatementStart, "SET TRAN ", true, false, new string[]
        {
            "ISOLATION",
        }),
        ("SET TRAN ISOLATION", SqlKeywordPosition.StatementStart, "SET TRAN ISOLATION ", true, false, new string[]
        {
            "LEVEL",
        }),
        ("SET TRAN ISOLATION LEVEL", SqlKeywordPosition.StatementStart, "SET TRAN ISOLATION LEVEL ", true, false, new string[]
        {
            "READ", "REPEATABLE", "SERIALIZABLE", "SNAPSHOT",
        }),
        ("SET TRAN ISOLATION LEVEL READ", SqlKeywordPosition.StatementStart, "SET TRAN ISOLATION LEVEL READ ", true, false, new string[]
        {
            "COMMITTED", "UNCOMMITTED",
        }),
        ("SET TRAN ISOLATION LEVEL REPEATABLE", SqlKeywordPosition.StatementStart, "SET TRAN ISOLATION LEVEL REPEATABLE ", true, false, new string[]
        {
            "READ",
        }),
        ("SET TRANSACTION", SqlKeywordPosition.StatementStart, "SET TRANSACTION ", true, false, new string[]
        {
            "ISOLATION",
        }),
        ("SET TRANSACTION ISOLATION", SqlKeywordPosition.StatementStart, "SET TRANSACTION ISOLATION ", true, false, new string[]
        {
            "LEVEL",
        }),
        ("SET TRANSACTION ISOLATION LEVEL", SqlKeywordPosition.StatementStart, "SET TRANSACTION ISOLATION LEVEL ", true, false, new string[]
        {
            "READ", "REPEATABLE", "SERIALIZABLE", "SNAPSHOT",
        }),
        ("SET TRANSACTION ISOLATION LEVEL READ", SqlKeywordPosition.StatementStart, "SET TRANSACTION ISOLATION LEVEL READ ", true, false, new string[]
        {
            "COMMITTED", "UNCOMMITTED",
        }),
        ("SET TRANSACTION ISOLATION LEVEL REPEATABLE", SqlKeywordPosition.StatementStart, "SET TRANSACTION ISOLATION LEVEL REPEATABLE ", true, false, new string[]
        {
            "READ",
        }),
        ("SET XACT_ABORT", SqlKeywordPosition.StatementStart, "SET XACT_ABORT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("SET IDENTITY_INSERT {name}", SqlKeywordPosition.StatementStart, "SET IDENTITY_INSERT t ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("CREATE", SqlKeywordPosition.StatementStart, "CREATE ", true, false, new string[]
        {
            "AGGREGATE", "APPLICATION", "ASSEMBLY", "ASYMMETRIC", "BROKER", "CERTIFICATE",
            "CLUSTERED", "COLUMN", "CONTRACT", "CREDENTIAL", "CRYPTOGRAPHIC", "DATABASE",
            "DEFAULT", "ENDPOINT", "EVENT", "EXTERNAL", "FEDERATION", "FULLTEXT", "FUNCTION",
            "INDEX", "LOGIN", "MASTER", "MATERIALIZED", "MESSAGE", "NONCLUSTERED", "PARTITION",
            "PRIMARY", "PROC", "PROCEDURE", "QUEUE", "REMOTE", "RESOURCE", "ROLE", "ROUTE",
            "RULE", "SCHEMA", "SEARCH", "SECURITY", "SELECTIVE", "SEQUENCE", "SERVER",
            "SERVICE", "STATISTICS", "SYMMETRIC", "SYNONYM", "TABLE", "TRIGGER", "TYPE",
            "UNIQUE", "USER", "VIEW", "WORKLOAD",
        }),
        ("ALTER", SqlKeywordPosition.StatementStart, "ALTER ", true, false, new string[]
        {
            "APPLICATION", "ASSEMBLY", "ASYMMETRIC", "AUTHORIZATION", "BROKER", "CERTIFICATE",
            "COLUMN", "CREDENTIAL", "CRYPTOGRAPHIC", "DATABASE", "ENDPOINT", "EVENT",
            "EXTERNAL", "FEDERATION", "FULLTEXT", "FUNCTION", "INDEX", "LOGIN", "MASTER",
            "MATERIALIZED", "MESSAGE", "PARTITION", "PROC", "PROCEDURE", "QUEUE", "REMOTE",
            "RESOURCE", "ROLE", "ROUTE", "SCHEMA", "SEARCH", "SECURITY", "SEQUENCE", "SERVER",
            "SERVICE", "SYMMETRIC", "TABLE", "TRIGGER", "USER", "VIEW",
        }),
        ("DROP", SqlKeywordPosition.StatementStart, "DROP ", true, false, new string[]
        {
            "AGGREGATE", "APPLICATION", "ASSEMBLY", "ASYMMETRIC", "BROKER", "CERTIFICATE",
            "COLUMN", "CONTRACT", "COUNTER", "CREDENTIAL", "CRYPTOGRAPHIC", "DATABASE",
            "DEFAULT", "ENDPOINT", "EVENT", "EXTERNAL", "FEDERATION", "FULLTEXT", "FUNCTION",
            "INDEX", "LOGIN", "MASTER", "MESSAGE", "PARTITION", "PROC", "PROCEDURE", "QUEUE",
            "REMOTE", "RESOURCE", "ROLE", "ROUTE", "RULE", "SCHEMA", "SEARCH", "SECURITY",
            "SENSITIVITY", "SEQUENCE", "SERVER", "SERVICE", "SIGNATURE", "STATISTICS",
            "SYMMETRIC", "SYNONYM", "TABLE", "TRIGGER", "TYPE", "USER", "VIEW", "WORKLOAD",
        }),
        ("CREATE OR ALTER", SqlKeywordPosition.StatementStart, "CREATE OR ALTER ", true, false, new string[]
        {
            "FUNCTION", "PROC", "PROCEDURE", "TRIGGER", "VIEW",
        }),
        ("ALTER TABLE {name}", SqlKeywordPosition.StatementStart, "ALTER TABLE t ", true, false, new string[]
        {
            "ADD", "ALTER", "CHECK", "DISABLE", "DROP", "ENABLE", "MERGE", "NOCHECK", "REBUILD",
            "SET", "SPLIT", "SWITCH", "WITH",
        }),
        ("ALTER DATABASE {name}", SqlKeywordPosition.StatementStart, "ALTER DATABASE t ", true, false, new string[]
        {
            "ADD", "COLLATE", "MODIFY", "PERFORM_CUTOVER", "REBUILD", "REMOVE", "SET",
        }),
        ("ALTER DATABASE {name} SET", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET ", true, false, new string[]
        {
            "ACCELERATED_DATABASE_RECOVERY", "ALLOW_SNAPSHOT_ISOLATION", "ANSI_NULL_DEFAULT",
            "ANSI_NULLS", "ANSI_PADDING", "ANSI_WARNINGS", "ARITHABORT", "AUTO_CLOSE",
            "AUTO_CREATE_STATISTICS", "AUTO_SHRINK", "AUTO_UPDATE_STATISTICS",
            "AUTO_UPDATE_STATISTICS_ASYNC", "AUTOMATIC_TUNING", "CHANGE_TRACKING",
            "COMPATIBILITY_LEVEL", "CONCAT_NULL_YIELDS_NULL", "CONTAINMENT",
            "CURSOR_CLOSE_ON_COMMIT", "CURSOR_DEFAULT", "DATA_RETENTION",
            "DATE_CORRELATION_OPTIMIZATION", "DB_CHAINING", "DEFAULT_FULLTEXT_LANGUAGE",
            "DEFAULT_LANGUAGE", "DELAYED_DURABILITY", "DISABLE_BROKER", "EMERGENCY",
            "ENABLE_BROKER", "ENCRYPTION", "ERROR_BROKER_CONVERSATIONS", "FILESTREAM", "HADR",
            "HONOR_BROKER_PRIORITY", "MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT",
            "MIXED_PAGE_ALLOCATION", "MULTI_USER", "NESTED_TRIGGERS", "NEW_BROKER",
            "NUMERIC_ROUNDABORT", "OFFLINE", "ONLINE", "OPTIMIZED_LOCKING", "PAGE_VERIFY",
            "PARAMETERIZATION", "PARTNER", "QUERY_STORE", "QUOTED_IDENTIFIER",
            "READ_COMMITTED_SNAPSHOT", "READ_ONLY", "READ_WRITE", "RECOVERY",
            "RECURSIVE_TRIGGERS", "REMOTE_DATA_ARCHIVE", "RESTRICTED_USER", "SINGLE_USER",
            "SUPPLEMENTAL_LOGGING", "TARGET_RECOVERY_TIME", "TEMPORAL_HISTORY_RETENTION",
            "TORN_PAGE_DETECTION", "TRANSFORM_NOISE_WORDS", "TRUSTWORTHY",
            "TWO_DIGIT_YEAR_CUTOFF", "VARDECIMAL_STORAGE_FORMAT", "WITNESS",
        }),
        ("ALTER DATABASE {name} SET ACCELERATED_DATABASE_RECOVERY", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET ACCELERATED_DATABASE_RECOVERY ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET ALLOW_SNAPSHOT_ISOLATION", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET ALLOW_SNAPSHOT_ISOLATION ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET ANSI_NULL_DEFAULT", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET ANSI_NULL_DEFAULT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET ANSI_NULLS", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET ANSI_NULLS ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET ANSI_PADDING", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET ANSI_PADDING ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET ANSI_WARNINGS", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET ANSI_WARNINGS ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET ARITHABORT", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET ARITHABORT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET AUTO_CLOSE", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET AUTO_CLOSE ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET AUTO_CREATE_STATISTICS", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET AUTO_CREATE_STATISTICS ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET AUTO_SHRINK", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET AUTO_SHRINK ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET AUTO_UPDATE_STATISTICS", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET AUTO_UPDATE_STATISTICS ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET AUTO_UPDATE_STATISTICS_ASYNC", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET AUTO_UPDATE_STATISTICS_ASYNC ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET AUTOMATIC_TUNING", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET AUTOMATIC_TUNING ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET CHANGE_TRACKING", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET CHANGE_TRACKING ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET COMPATIBILITY_LEVEL", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET COMPATIBILITY_LEVEL ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET CONCAT_NULL_YIELDS_NULL", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET CONCAT_NULL_YIELDS_NULL ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET CONTAINMENT", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET CONTAINMENT ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET CURSOR_CLOSE_ON_COMMIT", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET CURSOR_CLOSE_ON_COMMIT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET CURSOR_DEFAULT", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET CURSOR_DEFAULT ", true, false, new string[]
        {
            "GLOBAL", "LOCAL",
        }),
        ("ALTER DATABASE {name} SET DATA_RETENTION", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET DATA_RETENTION ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET DATE_CORRELATION_OPTIMIZATION", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET DATE_CORRELATION_OPTIMIZATION ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET DB_CHAINING", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET DB_CHAINING ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET DEFAULT_FULLTEXT_LANGUAGE", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET DEFAULT_FULLTEXT_LANGUAGE ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET DEFAULT_LANGUAGE", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET DEFAULT_LANGUAGE ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET DELAYED_DURABILITY", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET DELAYED_DURABILITY ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET ENCRYPTION", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET ENCRYPTION ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET FILESTREAM", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET FILESTREAM ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET HADR", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET HADR ", true, false, new string[]
        {
            "OFF", "RESUME", "SUSPEND",
        }),
        ("ALTER DATABASE {name} SET HONOR_BROKER_PRIORITY", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET HONOR_BROKER_PRIORITY ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET MIXED_PAGE_ALLOCATION", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET MIXED_PAGE_ALLOCATION ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET NESTED_TRIGGERS", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET NESTED_TRIGGERS ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET NUMERIC_ROUNDABORT", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET NUMERIC_ROUNDABORT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET OPTIMIZED_LOCKING", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET OPTIMIZED_LOCKING ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET PAGE_VERIFY", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET PAGE_VERIFY ", true, false, new string[]
        {
            "CHECKSUM", "NONE", "TORN_PAGE_DETECTION",
        }),
        ("ALTER DATABASE {name} SET PARAMETERIZATION", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET PARAMETERIZATION ", true, false, new string[]
        {
            "FORCED", "SIMPLE",
        }),
        ("ALTER DATABASE {name} SET PARTNER", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET PARTNER ", true, false, new string[]
        {
            "FAILOVER", "FORCE_SERVICE_ALLOW_DATA_LOSS", "OFF", "RESUME", "SAFETY", "SUSPEND",
            "TIMEOUT",
        }),
        ("ALTER DATABASE {name} SET QUERY_STORE", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET QUERY_STORE ", true, false, new string[]
        {
            "CLEAR",
        }),
        ("ALTER DATABASE {name} SET QUOTED_IDENTIFIER", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET QUOTED_IDENTIFIER ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET READ_COMMITTED_SNAPSHOT", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET READ_COMMITTED_SNAPSHOT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET RECOVERY", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET RECOVERY ", true, false, new string[]
        {
            "BULK_LOGGED", "FULL", "SIMPLE",
        }),
        ("ALTER DATABASE {name} SET RECURSIVE_TRIGGERS", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET RECURSIVE_TRIGGERS ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET REMOTE_DATA_ARCHIVE", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET REMOTE_DATA_ARCHIVE ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET SUPPLEMENTAL_LOGGING", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET SUPPLEMENTAL_LOGGING ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET TARGET_RECOVERY_TIME", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET TARGET_RECOVERY_TIME ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET TEMPORAL_HISTORY_RETENTION", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET TEMPORAL_HISTORY_RETENTION ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET TORN_PAGE_DETECTION", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET TORN_PAGE_DETECTION ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET TRANSFORM_NOISE_WORDS", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET TRANSFORM_NOISE_WORDS ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET TRUSTWORTHY", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET TRUSTWORTHY ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET TWO_DIGIT_YEAR_CUTOFF", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET TWO_DIGIT_YEAR_CUTOFF ", true, false, new string[]
        {
        }),
        ("ALTER DATABASE {name} SET VARDECIMAL_STORAGE_FORMAT", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET VARDECIMAL_STORAGE_FORMAT ", true, false, new string[]
        {
            "OFF", "ON",
        }),
        ("ALTER DATABASE {name} SET WITNESS", SqlKeywordPosition.StatementStart, "ALTER DATABASE t SET WITNESS ", true, false, new string[]
        {
            "OFF",
        }),
        ("BACKUP", SqlKeywordPosition.StatementStart, "BACKUP ", true, false, new string[]
        {
            "CERTIFICATE", "DATABASE", "LOG", "SERVICE",
        }),
        ("RESTORE", SqlKeywordPosition.StatementStart, "RESTORE ", true, false, new string[]
        {
            "DATABASE", "FILELISTONLY", "HEADERONLY", "LABELONLY", "LOG", "REWINDONLY",
            "SERVICE", "VERIFYONLY",
        }),
        ("ALTER INDEX {name} ON {name}", SqlKeywordPosition.StatementStart, "ALTER INDEX t ON t ", true, false, new string[]
        {
            "ABORT", "DISABLE", "FOR", "PAUSE", "REBUILD", "REORGANIZE", "RESUME", "SET",
            "WITH",
        }),
        ("INDEX {name} ON {name} ()", SqlKeywordPosition.Any, "CREATE INDEX t ON t (a) ", true, true, new string[]
        {
            "FILESTREAM_ON", "INCLUDE", "ON", "WHERE", "WITH",
        }),
        ("INCLUDE ()", SqlKeywordPosition.Any, "CREATE INDEX i ON t (a) INCLUDE (a) ", true, true, new string[]
        {
            "FILESTREAM_ON", "ON", "WHERE", "WITH",
        }),
        ("INDEX {name} ON {name} () WITH (*", SqlKeywordPosition.Any, "CREATE INDEX t ON t (a) WITH (", true, false, new string[]
        {
            "ALLOW_PAGE_LOCKS", "ALLOW_ROW_LOCKS", "BUCKET_COUNT", "COMPRESS_ALL_ROW_GROUPS",
            "COMPRESSION_DELAY", "DATA_COMPRESSION", "DROP_EXISTING", "FILESTREAM_ON",
            "FILLFACTOR", "IGNORE_DUP_KEY", "LOB_COMPACTION", "MAX_DURATION", "MAXDOP",
            "METRIC", "ONLINE", "OPTIMIZE_FOR_ARRAY_SEARCH", "OPTIMIZE_FOR_SEQUENTIAL_KEY",
            "ORDER", "PAD_INDEX", "RESUMABLE", "SORT_IN_TEMPDB", "STATISTICS_INCREMENTAL",
            "STATISTICS_NORECOMPUTE", "TYPE", "WAIT_AT_LOW_PRIORITY", "XML_COMPRESSION",
        }),
        ("INCLUDE () WITH (*", SqlKeywordPosition.Any, "CREATE INDEX i ON t (a) INCLUDE (a) WITH (", true, false, new string[]
        {
            "ALLOW_PAGE_LOCKS", "ALLOW_ROW_LOCKS", "BUCKET_COUNT", "COMPRESS_ALL_ROW_GROUPS",
            "COMPRESSION_DELAY", "DATA_COMPRESSION", "DROP_EXISTING", "FILESTREAM_ON",
            "FILLFACTOR", "IGNORE_DUP_KEY", "LOB_COMPACTION", "MAX_DURATION", "MAXDOP",
            "METRIC", "ONLINE", "OPTIMIZE_FOR_ARRAY_SEARCH", "OPTIMIZE_FOR_SEQUENTIAL_KEY",
            "ORDER", "PAD_INDEX", "RESUMABLE", "SORT_IN_TEMPDB", "STATISTICS_INCREMENTAL",
            "STATISTICS_NORECOMPUTE", "TYPE", "WAIT_AT_LOW_PRIORITY", "XML_COMPRESSION",
        }),
        ("TRIGGER {name} ON {name}", SqlKeywordPosition.Any, "CREATE TRIGGER t ON t ", true, false, new string[]
        {
            "AFTER", "FOR", "INSTEAD", "WITH",
        }),
        ("TRIGGER {name} ON {name} AFTER", SqlKeywordPosition.Any, "CREATE TRIGGER t ON t AFTER ", true, false, new string[]
        {
            "DELETE", "INSERT", "UPDATE",
        }),
        ("TRIGGER {name} ON {name} FOR", SqlKeywordPosition.Any, "CREATE TRIGGER t ON t FOR ", true, false, new string[]
        {
            "DELETE", "INSERT", "UPDATE",
        }),
        ("TRIGGER {name} ON {name} INSTEAD", SqlKeywordPosition.Any, "CREATE TRIGGER t ON t INSTEAD ", true, false, new string[]
        {
            "OF",
        }),
        ("TRIGGER {name} ON {name} WITH", SqlKeywordPosition.Any, "CREATE TRIGGER t ON t WITH ", true, false, new string[]
        {
            "EXEC", "EXECUTE",
        }),
        ("EXECUTE AS", SqlKeywordPosition.StatementStart, "EXECUTE AS ", true, false, new string[]
        {
            "CALLER", "LOGIN", "USER",
        }),
        ("EXEC AS", SqlKeywordPosition.StatementStart, "EXEC AS ", true, false, new string[]
        {
            "CALLER", "LOGIN", "USER",
        }),
        ("WITH EXECUTE AS", SqlKeywordPosition.Any, "CREATE PROCEDURE p WITH EXECUTE AS ", true, false, new string[]
        {
            "CALLER", "OWNER", "SELF",
        }),
        ("WITH EXEC AS", SqlKeywordPosition.Any, "CREATE PROCEDURE p WITH EXEC AS ", true, false, new string[]
        {
            "CALLER", "OWNER", "SELF",
        }),
        ("ON DELETE", SqlKeywordPosition.Any, "CREATE TABLE t (a int REFERENCES u (a) ON DELETE ", true, false, new string[]
        {
            "CASCADE", "NO", "SET",
        }),
        ("ON DELETE CASCADE", SqlKeywordPosition.Any, "CREATE TABLE t (a int REFERENCES u (a) ON DELETE CASCADE ", true, false, new string[]
        {
            "CHECK", "CONSTRAINT", "DEFAULT", "FOREIGN", "IDENTITY", "INDEX", "NOT", "NULL",
            "ON", "PRIMARY", "REFERENCES", "UNIQUE",
        }),
        ("ON DELETE NO", SqlKeywordPosition.Any, "CREATE TABLE t (a int REFERENCES u (a) ON DELETE NO ", true, false, new string[]
        {
            "ACTION",
        }),
        ("ON DELETE SET", SqlKeywordPosition.Any, "CREATE TABLE t (a int REFERENCES u (a) ON DELETE SET ", true, false, new string[]
        {
            "DEFAULT", "NULL",
        }),
        ("ON UPDATE", SqlKeywordPosition.Any, "CREATE TABLE t (a int REFERENCES u (a) ON UPDATE ", true, false, new string[]
        {
            "CASCADE", "NO", "SET",
        }),
        ("ON UPDATE CASCADE", SqlKeywordPosition.Any, "CREATE TABLE t (a int REFERENCES u (a) ON UPDATE CASCADE ", true, false, new string[]
        {
            "CHECK", "CONSTRAINT", "DEFAULT", "FOREIGN", "IDENTITY", "INDEX", "NOT", "NULL",
            "ON", "PRIMARY", "REFERENCES", "UNIQUE",
        }),
        ("ON UPDATE NO", SqlKeywordPosition.Any, "CREATE TABLE t (a int REFERENCES u (a) ON UPDATE NO ", true, false, new string[]
        {
            "ACTION",
        }),
        ("ON UPDATE SET", SqlKeywordPosition.Any, "CREATE TABLE t (a int REFERENCES u (a) ON UPDATE SET ", true, false, new string[]
        {
            "DEFAULT", "NULL",
        }),
        ("WAITFOR", SqlKeywordPosition.StatementStart, "WAITFOR ", true, false, new string[]
        {
            "DELAY", "TIME",
        }),
        ("DECLARE {name} CURSOR", SqlKeywordPosition.StatementStart, "DECLARE t CURSOR ", true, false, new string[]
        {
            "DYNAMIC", "FAST_FORWARD", "FOR", "FORWARD_ONLY", "GLOBAL", "KEYSET", "LOCAL",
            "OPTIMISTIC", "READ_ONLY", "SCROLL", "SCROLL_LOCKS", "STATIC", "TYPE_WARNING",
        }),
        ("FETCH", SqlKeywordPosition.StatementStart, "FETCH ", false, false, new string[]
        {
            "ABSOLUTE", "FIRST", "FROM", "GLOBAL", "LAST", "NEXT", "PRIOR", "RELATIVE",
        }),
        ("FOR", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail, "SELECT a FOR ", true, false, new string[]
        {
            "BROWSE", "JSON", "READ", "UPDATE", "XML",
        }),
        ("FOR JSON", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail, "SELECT a FOR JSON ", true, false, new string[]
        {
            "AUTO", "PATH",
        }),
        ("FOR READ", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail, "SELECT a FOR READ ", true, false, new string[]
        {
            "ONLY",
        }),
        ("FOR XML", SqlKeywordPosition.SelectListTail | SqlKeywordPosition.TableSourceTail | SqlKeywordPosition.ExpressionTail | SqlKeywordPosition.OrderByTail | SqlKeywordPosition.GroupByTail, "SELECT a FOR XML ", true, false, new string[]
        {
            "AUTO", "EXPLICIT", "PATH", "RAW",
        }),
        ("FOR", SqlKeywordPosition.TableSourceTail, "SELECT * FROM t FOR ", true, false, new string[]
        {
            "BROWSE", "JSON", "PATH", "READ", "SYSTEM_TIME", "UPDATE", "XML",
        }),
        ("FOR SYSTEM_TIME", SqlKeywordPosition.TableSourceTail, "SELECT * FROM t FOR SYSTEM_TIME ", true, false, new string[]
        {
            "ALL", "AS", "BETWEEN", "CONTAINED", "FROM",
        }),
        ("FOR SYSTEM_TIME AS", SqlKeywordPosition.TableSourceTail, "SELECT * FROM t FOR SYSTEM_TIME AS ", true, false, new string[]
        {
            "OF",
        }),
        ("FOR SYSTEM_TIME BETWEEN", SqlKeywordPosition.TableSourceTail, "SELECT * FROM t FOR SYSTEM_TIME BETWEEN ", true, false, new string[]
        {
        }),
        ("FOR SYSTEM_TIME CONTAINED", SqlKeywordPosition.TableSourceTail, "SELECT * FROM t FOR SYSTEM_TIME CONTAINED ", true, false, new string[]
        {
            "IN",
        }),
        ("FOR SYSTEM_TIME FROM", SqlKeywordPosition.TableSourceTail, "SELECT * FROM t FOR SYSTEM_TIME FROM ", true, false, new string[]
        {
        }),
        ("CURSOR FOR", SqlKeywordPosition.Any, "DECLARE c CURSOR FOR ", true, false, new string[]
        {
            "SELECT", "WITH",
        }),
        ("NEXT VALUE FOR", SqlKeywordPosition.Any, "SELECT NEXT VALUE FOR ", false, false, new string[]
        {
        }),
        ("DEFAULT {value} FOR", SqlKeywordPosition.Any, "ALTER TABLE t ADD DEFAULT 1 FOR ", false, false, new string[]
        {
        }),
        ("USER {name} FOR", SqlKeywordPosition.Any, "CREATE USER t FOR ", true, false, new string[]
        {
            "ASYMMETRIC", "CERTIFICATE", "EXTERNAL", "LOGIN",
        }),
        ("SYNONYM {name} FOR", SqlKeywordPosition.Any, "CREATE SYNONYM t FOR ", false, false, new string[]
        {
        }),
        ("NOT FOR", SqlKeywordPosition.Any, "CREATE TABLE t (a int IDENTITY NOT FOR ", true, false, new string[]
        {
            "REPLICATION",
        }),
        ("GROUP BY", SqlKeywordPosition.Any, "SELECT a FROM t GROUP BY ", false, false, new string[]
        {
            "ALL", "CASE", "COALESCE", "CONVERT", "CURRENT_DATE", "CURRENT_TIMESTAMP",
            "CURRENT_USER", "GROUPING", "LEFT", "NEXT", "NULL", "NULLIF", "RIGHT",
            "SESSION_USER", "SYSTEM_USER", "TRY_CONVERT", "USER", "ROLLUP", "CUBE",
            "GROUPING SETS",
        }),
        ("TOP {value} WITH", SqlKeywordPosition.Any, "SELECT TOP 1 WITH ", true, false, new string[]
        {
            "APPROX", "APPROXIMATE", "TIES",
        }),
        ("PERCENT WITH", SqlKeywordPosition.Any, "SELECT TOP 10 PERCENT WITH ", true, false, new string[]
        {
            "APPROX", "APPROXIMATE", "TIES",
        }),
        ("AT TIME", SqlKeywordPosition.Any, "SELECT a AT TIME ", true, false, new string[]
        {
            "ZONE",
        }),
        ("NOT MATCHED", SqlKeywordPosition.Any, "MERGE t USING s ON 1 = 1 WHEN NOT MATCHED ", true, false, new string[]
        {
            "AND", "BY", "THEN",
        }),
        ("MATCHED BY", SqlKeywordPosition.Any, "MERGE t USING s ON 1 = 1 WHEN NOT MATCHED BY ", true, false, new string[]
        {
            "SOURCE", "TARGET",
        }),
        ("OFFSET {value} ROWS", SqlKeywordPosition.Any, "SELECT a FROM t ORDER BY a OFFSET 1 ROWS ", true, true, new string[]
        {
            "FOR", "OPTION", "FETCH",
        }),
        ("OFFSET {value} ROW", SqlKeywordPosition.Any, "SELECT a FROM t ORDER BY a OFFSET 1 ROW ", true, true, new string[]
        {
            "FOR", "OPTION", "FETCH",
        }),
        ("ROWS FETCH", SqlKeywordPosition.Any, "SELECT a FROM t ORDER BY a OFFSET 0 ROWS FETCH ", true, false, new string[]
        {
            "APPROX", "APPROXIMATE", "FIRST", "FROM", "NEXT",
        }),
        ("ROW FETCH", SqlKeywordPosition.Any, "SELECT a FROM t ORDER BY a OFFSET 0 ROW FETCH ", true, false, new string[]
        {
            "APPROX", "APPROXIMATE", "FIRST", "FROM", "NEXT",
        }),
        ("FETCH NEXT {value}", SqlKeywordPosition.Any, "SELECT a FROM t ORDER BY a OFFSET 0 ROWS FETCH NEXT 1 ", true, false, new string[]
        {
            "COLLATE", "ROW", "ROWS",
        }),
        ("FETCH FIRST {value}", SqlKeywordPosition.Any, "SELECT a FROM t ORDER BY a OFFSET 0 ROWS FETCH FIRST 1 ", true, false, new string[]
        {
            "COLLATE", "ROW", "ROWS",
        }),
        ("FETCH NEXT {value} ROWS", SqlKeywordPosition.Any, "SELECT a FROM t ORDER BY a OFFSET 0 ROWS FETCH NEXT 1 ROWS ", true, false, new string[]
        {
            "ONLY",
        }),
        ("FETCH NEXT {value} ROW", SqlKeywordPosition.Any, "SELECT a FROM t ORDER BY a OFFSET 0 ROWS FETCH NEXT 1 ROW ", true, false, new string[]
        {
            "ONLY",
        }),
        ("FETCH FIRST {value} ROWS", SqlKeywordPosition.Any, "SELECT a FROM t ORDER BY a OFFSET 0 ROWS FETCH FIRST 1 ROWS ", true, false, new string[]
        {
            "ONLY",
        }),
        ("FETCH FIRST {value} ROW", SqlKeywordPosition.Any, "SELECT a FROM t ORDER BY a OFFSET 0 ROWS FETCH FIRST 1 ROW ", true, false, new string[]
        {
            "ONLY",
        }),
        ("ROWS", SqlKeywordPosition.Any, "SELECT SUM(a) OVER (ORDER BY a ROWS ", true, false, new string[]
        {
            "BETWEEN", "CURRENT", "UNBOUNDED",
        }),
        ("RANGE", SqlKeywordPosition.Any, "SELECT SUM(a) OVER (ORDER BY a RANGE ", true, false, new string[]
        {
            "BETWEEN", "CURRENT", "UNBOUNDED",
        }),
        ("ROWS BETWEEN", SqlKeywordPosition.Any, "SELECT SUM(a) OVER (ORDER BY a ROWS BETWEEN ", true, false, new string[]
        {
            "CURRENT", "UNBOUNDED",
        }),
        ("RANGE BETWEEN", SqlKeywordPosition.Any, "SELECT SUM(a) OVER (ORDER BY a RANGE BETWEEN ", true, false, new string[]
        {
            "CURRENT", "UNBOUNDED",
        }),
        ("UNBOUNDED", SqlKeywordPosition.Any, "SELECT SUM(a) OVER (ORDER BY a ROWS BETWEEN UNBOUNDED ", true, false, new string[]
        {
            "FOLLOWING", "PRECEDING",
        }),
        ("PRECEDING AND", SqlKeywordPosition.Any, "SELECT SUM(a) OVER (ORDER BY a ROWS BETWEEN UNBOUNDED PRECEDING AND ", true, false, new string[]
        {
            "CURRENT", "UNBOUNDED",
        }),
        ("ROWS CURRENT", SqlKeywordPosition.Any, "SELECT SUM(a) OVER (ORDER BY a ROWS CURRENT ", true, false, new string[]
        {
            "ROW",
        }),
        ("RANGE CURRENT", SqlKeywordPosition.Any, "SELECT SUM(a) OVER (ORDER BY a RANGE CURRENT ", true, false, new string[]
        {
            "ROW",
        }),
        ("BETWEEN CURRENT", SqlKeywordPosition.Any, "SELECT SUM(a) OVER (ORDER BY a ROWS BETWEEN CURRENT ", true, false, new string[]
        {
            "ROW",
        }),
        ("AND CURRENT", SqlKeywordPosition.Any, "SELECT SUM(a) OVER (ORDER BY a ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ", true, false, new string[]
        {
            "ROW",
        }),
    };
}
