using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SqlAssist.KeywordGenerator;

/// <summary>產物 SqlKeywordCatalog.Generated.cs 的全部內容；產生器的每一階段各填一部分。</summary>
internal sealed class CatalogData
{
    public string ScriptDomVersion { get; init; } = string.Empty;

    public string ParserName { get; init; } = string.Empty;

    public int NonReservedSupplementCount { get; init; }

    /// <summary>關鍵字與各自可以出現的位置，照位置表的順序。</summary>
    public IReadOnlyList<KeyValuePair<string, IReadOnlyList<string>>> Keywords { get; init; } = [];

    public IReadOnlyList<PositionTemplate> Templates { get; init; } = [];

    public IReadOnlyList<string> Reserved { get; init; } = [];

    public IReadOnlyList<string> ItemEndings { get; init; } = [];

    public IReadOnlyList<StatementEnding> StatementEndings { get; init; } = [];

    public IReadOnlyList<ProbedPhrase> Phrases { get; init; } = [];

    public IReadOnlyList<AdditivePhrase> Additive { get; init; } = [];

    /// <summary>帶尾巴的附加片語，照片語表的順序。</summary>
    public IReadOnlyList<ProbedPhrase> TailAdditive { get; init; } = [];

    public IReadOnlyList<(string Kind, bool AlsoWords, bool SchemaQualified)> CreatedKinds { get; init; } = [];
}

/// <summary>把 <see cref="CatalogData"/> 寫成 C#；格式固定，探測結果沒變時重跑的產物逐字相同。</summary>
internal static class CatalogWriter
{
    // 清單一行最多到這一欄就換行。
    private const int LineWidth = 96;

    public static string Write(CatalogData data)
    {
        var builder = new StringBuilder();

        void Line(string text = "")
        {
            builder.Append(text).Append('\n');
        }

        Line("// <auto-generated />");
        Line("//");
        Line("// 由 tools/Generate-Keywords.ps1 產生，請勿手動編輯。");
        Line($"// 來源：Microsoft.SqlServer.TransactSql.ScriptDom {data.ScriptDomVersion}（{data.ParserName}）");
        Line("//");
        Line("// 關鍵字取自 TSqlTokenType 的成員名稱並以 tokenizer 回驗，");
        Line($"// 另加產生器 Data/KeywordSupplements.cs 的 {data.NonReservedSupplementCount} 個非保留字；");
        Line("// 位置則是把每個關鍵字塞進樣板剖析、依錯誤碼判定得到的。");
        Line("//");
        Line("// 保留字是另外探測的一份：把字塞進識別字的洞裡，剖析器拒收的才算，");
        Line("// 因此它與上面的關鍵字清單互有出入——兩邊都有對方沒有的字。");
        Line();
        Line("using System.Collections.Generic;");
        Line();
        Line("namespace SqlAssist.Core.Keywords;");
        Line();

        // 刻意不做成 SqlKeywordCatalog 的 partial：同一個類別的靜態欄位若分散在兩個檔案，
        // 初始化順序由編譯順序決定，SqlKeywordCatalog 的衍生字典就可能在資料還是 null 時先跑。
        // 拆成獨立類別之後，跨類別的靜態初始化由「第一次存取」觸發，順序才有保證。
        Line("/// <summary>產生出來的關鍵字資料；請由 <see cref=\"SqlKeywordCatalog\"/> 取用。</summary>");
        Line("internal static class SqlKeywordCatalogData");
        Line("{");
        Line("    /// <summary>產生這份目錄所用的 ScriptDom 版本。</summary>");
        Line($"    internal const string SourceVersion = {Quote(data.ScriptDomVersion)};");
        Line();
        Line("    /// <summary>全部關鍵字，以及各自可以出現的位置。</summary>");
        Line("    internal static readonly KeyValuePair<string, SqlKeywordPosition>[] Keywords =");
        Line("    {");

        foreach (var keyword in data.Keywords)
        {
            Line($"        new({Quote(keyword.Key)}, {Flags(keyword.Value)}),");
        }

        Line("    };");
        Line();
        Line("    /// <summary>定位置所用的樣板：每個位置與它的樣板文字。</summary>");
        Line("    /// <remarks>");
        Line("    /// 執行期用不到，輸出來是為了讓測試逐條回驗：分析器對樣板文字回報的位置");
        Line("    /// 必須含那個位置，兩邊說的才是同一個位置。");
        Line("    /// </remarks>");
        Line("    internal static readonly KeyValuePair<SqlKeywordPosition, string>[] Templates =");
        Line("    {");

        foreach (var position in data.Templates)
        {
            foreach (var template in position.Templates)
            {
                Line($"        new(SqlKeywordPosition.{position.Position}, {Quote(template)}),");
            }
        }

        Line("    };");
        Line();
        Line("    /// <summary>不能直接當識別字書寫、插入時一定要加方括號的字。</summary>");
        Line("    internal static readonly string[] ReservedIdentifiers =");
        Line("    {");
        AppendWrapped(builder, "       ", data.Reserved);
        Line("    };");
        Line();
        Line("    /// <summary>本身就把前一格開的那一項寫完的字（NULL、DESC）。</summary>");
        Line("    internal static readonly string[] ItemEndings =");
        Line("    {");
        AppendWrapped(builder, "       ", data.ItemEndings);
        Line("    };");
        Line();
        Line("    /// <summary>寫完一整句的字，以及前一格在哪些位置時寫完那一句就只剩下一句可接。</summary>");
        Line("    internal static readonly KeyValuePair<string, SqlKeywordPosition>[] StatementEndings =");
        Line("    {");

        foreach (var ending in data.StatementEndings)
        {
            Line($"        new({Quote(ending.Word)}, {Flags(ending.Closes)}),");
        }

        Line("    };");
        Line();
        Line("    /// <summary>子句片語：游標前的尾巴、探測文字、是否封閉、是否收變數、是否是名稱格、語句到那裡是否已經完整，以及那裡接得上的字。</summary>");
        Line("    /// <remarks>");
        Line("    /// 探測文字執行期用不到，輸出來是為了讓測試逐條回驗：片語比對對那段文字");
        Line("    /// 必須認出同一個片語，兩邊說的才是同一個位置。");
        Line("    /// </remarks>");
        Line("    internal static readonly (string Pattern, SqlKeywordPosition After, string Probe, bool Closed, bool TakesVariable, bool TakesName, bool EndsStatement, string[] Words)[] ClausePhrases =");
        Line("    {");

        foreach (var phrase in data.Phrases)
        {
            Line($"        ({Quote(phrase.Pattern)}, {Flags(phrase.After)}, {Quote(phrase.Probe)}, {Bool(phrase.Closed)}, {Bool(phrase.TakesVariable)}, {Bool(phrase.TakesName)}, {Bool(phrase.EndsStatement)}, new string[]");
            Line("        {");
            AppendWrapped(builder, "           ", phrase.Words);
            Line("        }),");
        }

        Line("    };");
        Line();
        Line("    /// <summary>");
        Line("    /// 附加片語：比對永遠是「可能」，只把字加進那一格。尾巴是空的只認位置，把關鍵字目錄給不了的片語開頭加進那個位置；");
        Line("    /// 帶尾巴的照尾巴比對（剖析器分不出字的權限名稱、模組本體的 AS）。");
        Line("    /// </summary>");
        Line("    internal static readonly (string Pattern, SqlKeywordPosition After, string Probe, string[] Words)[] AdditivePhrases =");
        Line("    {");

        foreach (var additive in data.Additive)
        {
            Line($"        (\"\", SqlKeywordPosition.{additive.After}, {Quote(additive.Probe)}, new string[] {{ {string.Join(", ", additive.Words.Select(Quote))} }}),");
        }

        foreach (var phrase in data.TailAdditive)
        {
            Line($"        ({Quote(phrase.Pattern)}, {Flags(phrase.After)}, {Quote(phrase.Probe)}, new string[] {{ {string.Join(", ", phrase.Words.Select(Quote))} }}),");
        }

        Line("    };");
        Line();
        Line("    /// <summary>");
        Line("    /// CREATE 之後寫到這幾個字，下一格是物件的名稱；AlsoWords 是那一格除了名稱還接不接得上片語的字");
        Line("    /// （CREATE DATABASE 之後還有 SCOPED），SchemaQualified 是名稱寫不寫得出結構描述（CREATE PROCEDURE dbo.p）。");
        Line("    /// </summary>");
        Line("    internal static readonly (string Kind, bool AlsoWords, bool SchemaQualified)[] CreatedKinds =");
        Line("    {");

        foreach (var (kind, alsoWords, schemaQualified) in data.CreatedKinds)
        {
            Line($"        ({Quote(kind)}, {Bool(alsoWords)}, {Bool(schemaQualified)}),");
        }

        Line("    };");
        Line("}");
        return builder.ToString();
    }

    internal static string Quote(string text)
    {
        return "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }

    /// <summary>位置旗標；一個位置都沒有是 None。</summary>
    internal static string Flags(IEnumerable<string> positions)
    {
        var flags = positions.Select(position => "SqlKeywordPosition." + position).ToList();
        return flags.Count == 0 ? "SqlKeywordPosition.None" : string.Join(" | ", flags);
    }

    /// <summary>字串清單接成幾行，每行不超過 <see cref="LineWidth"/> 欄。</summary>
    internal static void AppendWrapped(StringBuilder builder, string indent, IEnumerable<string> words)
    {
        var line = indent;

        foreach (var word in words)
        {
            var entry = " " + Quote(word) + ",";

            if (line.Length + entry.Length > LineWidth)
            {
                builder.Append(line).Append('\n');
                line = indent;
            }

            line += entry;
        }

        if (line.Trim().Length > 0)
        {
            builder.Append(line).Append('\n');
        }
    }

    private static string Bool(bool value)
    {
        return value ? "true" : "false";
    }
}
